- .changeset/proud-jobs-yawn.md
- core/src/contract/contract.spec.ts
- core/src/contract/contract.ts
Fix bug where overloaded functions were not properly handled
We would overwrite previous functions instead of appending overloaded functions to the abi
For fix we filter for overloaded functions. This is inefficient and should be improved in future to scale at N instead of N^2
Unit test
> :bug: fix(core): Fix overloaded abis

- .changeset/nine-socks-remain.md
- bundlers/bundler/src/solc/solcPlugin.ts
- core/src/contract/contract.spec.ts
- core/src/contract/contract.ts
Add support for bytecode in EVMts contracts.  This enables usage of EVMts contracts to deploy in JS using viem or ethers
Unit tests
> :sparkles: feat: Add bytecode to EVMts contract

- nx.json
Nx cache was in bad state from forgetting to include types folder in build output
> :construction_worker: fix(build): Add types folder to build output

- .changeset/cyan-cherries-design.md
- core/src/contract/contract.ts
- Make chainId accept a number instead of only string
- change bytecode to `0x${string}` to match wagmi type
None assuming this works
> :bug: fix: Make types for EVMtsContract better

- .github/workflows/coverage.yml
Use run-many so coverage reports are always created even if cached
> :construction_worker: fix: Use nx run-many instead of affected for coverage reports

- .changeset/mighty-schools-deliver.md
- bundlers/config/src/EVMtsConfig.ts
The old zod validator required every etherscan network to be defined.
- use z.object().partial() instead of z.record()
100% test coverage for this package
> :bug: fix(config): Make etherscan api keys partial

- .changeset/serious-shrimps-shave.md
- bundlers/bundler/src/unplugin.spec.ts
- bundlers/bundler/src/unplugin.ts
Didn't seem to be causing issues but using '.' instead of process.cwd() is not idiomatic and may have caused bugs
> :bug: fix(bundler): Use process.cwd() instead of '.'

- .changeset/fluffy-sloths-grow.md
- config/src/loadConfig.spec.ts
- config/src/loadConfig.ts
- config/vitest.config.ts
Added support for jsconfig.json to EVMts. If a jsconfig.json file exists evmts will autodetect it the same way it autodetects tsconfig.json
> :sparkles: feat(config): Add jsconfig.json support to EVMts

- examples/mud/package.json
- examples/svelte-ethers/package.json
- nx.json
Remove prepare script because it runs automatically after pnpm install. This breaks docs site on vercel needlessly from no forge being installed
> :construction_worker: fix(mud): remove prepare script

- .changeset/friendly-cooks-juggle.md
- README.md
- bundlers/bundler/src/bundler.spec.ts
- bundlers/bundler/src/runtime/generateEvmtsBody.spec.ts
- bundlers/bundler/src/runtime/generateEvmtsBody.ts
- bundlers/bundler/src/runtime/generateEvmtsBodyDts.ts
- bundlers/bundler/src/runtime/generateRuntimeSync.spec.ts
- bundlers/bundler/src/solc/compileContracts.spec.ts
- bundlers/bundler/src/solc/compileContracts.ts
- bundlers/bundler/src/solc/resolveArtifacts.spec.ts
- bundlers/bundler/src/solc/resolveArtifacts.ts
- bundlers/bundler/src/solc/resolveArtifactsSync.spec.ts
- bundlers/bundler/src/solc/resolveArtifactsSync.ts
- bundlers/bundler/src/solc/solc.ts
- bundlers/rollup/README.md
- bundlers/vite/README.md
- cli/src/commands/generate/generate.ts
- core/src/EvmtsContract.ts
- core/src/event/eventFactory.spec.ts
- core/src/evmtsContractFactory.spec.ts
- core/src/evmtsContractFactory.ts
- core/src/read/readFactory.spec.ts
- core/src/write/writeFactory.spec.ts
- ethers/src/createEthersContract.spec.ts
- examples/vite/src/contracts/external/DAI.mjs
- examples/vite/src/contracts/external/DAI.sol.mjs
Make solc only return abi natspec and ast
Solc compilation is needlessly expensive because we are compiling bytecode and everything else as well. Bytecode is currently niche use case so remove to improve peformance
Existing tests
> :zap: feat(bundler): Increase peformance by only returning the ast abi and userdoc

- bundlers/bundler/src/createCache.d.ts
- bundlers/bundler/src/index.js
Be explicit about the public api of bundler instead of `export * from './foo'`.
https://github.com/evmts/evmts-monorepo/issues/586
> :recycle: chore(bundler): Explicitly export public api

- config/scripts/runFixture.ts
Throw in dev server if the fixture is supposed to throw but doesnt
> :bug: fix: Throw if expecting error in dev server fixture

- config/docs/modules/defineConfig.md
- config/src/defineConfig.js
- package.json
missing ``` was making jsdoc generated docs wrong
> :memo: fix: jsdoc missing closing ```

- .changeset/yellow-birds-type.md
- vm/package.json
types folder was missing from @evmts/vm package when published to npm causing the types to not resolve
> :bug: Fix(vm): Add types to files in package.json

- bundler/unplugin/src/evmtsUnplugin.spec.ts
Test is broken because the version is hardcoded. This is because we can't import json with no bundler mode. No idea how to deal with this other than adding a build step for now just gonna ignore the issue.
> :white_check_mark: Fix: Remove broken test from unplugin

- packages/core/src/index.ts
After changing module to verbatin module syntax the type exports broke. Fix by explicitly exporting the api
> :bug: Fix(core): Fix type exports of EvmtsContract

- .changeset/warm-glasses-glow.md
- bundler/unplugin/src/evmtsUnplugin.js
- bundler/unplugin/src/evmtsUnplugin.spec.ts
By not including a loadInclude the webpack plugin will attempt to parse non javascript files including html files.
> :bug: Fix(webpack-plugin): Add loadInclude to unplugin

- rome.json
Not ignoring nx file caused it to lint a huge file
> :construction_worker: Fix: Fix rome.json not ignoring nx

- .changeset/smooth-fishes-study.md
- bundler/bun/src/bunFileAccessObject.js
- bundler/compiler/src/compiler/compileContracts.spec.ts
- bundler/compiler/src/compiler/compileContractsSync.spec.ts
- bundler/compiler/src/resolveArtifacts.spec.ts
- bundler/compiler/src/resolveArtifactsSync.spec.ts
- bundler/compiler/src/types.ts
- bundler/compiler/src/utils/resolvePromise.js
- bundler/compiler/src/utils/resolvePromise.spec.ts
- bundler/config/src/tsconfig/loadTsConfig.js
- bundler/resolutions/src/moduleFactory.spec.ts
- bundler/resolutions/src/types.ts
- bundler/resolutions/src/utils/resolveSafe.js
- bundler/resolutions/src/utils/resolveSafe.spec.ts
- bundler/resolutions/src/utils/safeFao.js
- bundler/resolutions/src/utils/safeFao.spec.ts
I previously lazily used existsSync because no promise based exists existed. Improve peformance by creating exists using fs.access
> :zap: Feat: Replace existsSync with exists in async bundler routines

- bundler/base/src/resolveModuleAsync.js
- examples/svelte-ethers/package.json
- examples/vite/package.json
- pnpm-lock.yaml
Svelte build had a bad version of open zepplen that didn't run in ci because the package was missing build:dist
> :bug: Fix: Broken openzepplen version in svelte build

- extensions/opstack/package.json
Bug in the nx cache has caused the opstack tests to be broken for a while now. The tests do not mine blocks and thus should have broken on the mine blocks pr
Disable for now
> :clown_face: Chore: Disable opstack tests for now

- packages/actions/src/tevm/contractHandler.js
- packages/memory-client/src/test/viemPublicActions.spec.ts
Fixes a bug where reverts without messages throw
Add error transparency when decoding revert messages in TEVM contract handler, enriching the debugging process.
Improved error handling in contractHandler.js, added a try-catch block to safely handle decoding revert messages that can cause unforeseen exceptions. Now, if there is an issue during decoding, an appropriate message is logged.
1. Clone the PR branch
2. Install dependencies: `npm install`
3. Run the tests for contractHandler: `npm run test-contractHandler`
Better error transparency during decoding revert messages in TEVM contract handlers can help the debugging process, especially in complex TEVM applications where revert messages can be cryptic and can contain errors themselves.
--- …
> :loud_sound: Fix: add try catch to revert data decoding

- flake.nix
What I need to do is add instructions to getting started
```
nix shell nixpkgs#direnv
direnv allow
```
> fix: remove direnv pkg

- .changeset/empty-plums-pretend.md
- .changeset/nice-walls-fail.md
- packages/actions/src/eth/ethGetLogsHandler.js
- packages/actions/src/eth/utils/parseBlockParam.js
- packages/actions/src/eth/utils/parseBlockParam.spec.ts
> :bug: Fix: eth_getLogs not hadnling hex numbers correct

- .changeset/empty-plums-pretend.md
- .changeset/nice-walls-fail.md
- packages/actions/src/eth/ethGetLogsHandler.js
- packages/actions/src/eth/utils/parseBlockParam.js
- packages/actions/src/eth/utils/parseBlockParam.spec.ts
> 🐛 fix: eth get_logs not handling hex numbers

- .changeset/light-cheetahs-tie.md
- packages/procedures/src/eth/ethGetTransactionCountProcedure.js
- packages/procedures/src/eth/ethGetTransactionCountProcedure.spec.ts
> :white_check_mark: Test: Add eth_getTransactionCount tests

- .changeset/famous-bottles-fail.md
- packages/actions/src/anvil/anvilImpersonateAccount.spec.ts
- packages/actions/src/anvil/anvilLoadStateProcedure.spec.ts
- packages/actions/src/eth/ethNewBlockFilterProcedure.spec.ts
- packages/actions/src/eth/ethSendTransactionProcedure.spec.ts
- packages/node/src/createTevmNode.js
> :test_tube: Test: Add more test coverage to tevm actions

- .changeset/floppy-forks-yell.md
- cli/package.json
Fixed a bug in the CLI package where the distribution files were not being published correctly. Updated the build script to use `build:dist` and added a new `build:app` script that contains the previous build logic.
Verified that the CLI distribution files are now properly published.
> fix: Cli not including built files on npm

- packages/txpool/src/TxPool.spec.ts
- src/Evm/Frame_test.zig
- src/Evm/evm.zig
- src/Interpreter/interpreter.zig
- src/Types/U256.spec.ts
- src/Types/U256.ts
- src/Types/common-int.ts
- src/root.zig
Implemented a comprehensive set of EVM opcodes in the interpreter module. This includes:
- Added `ExecutionError` type for handling execution flow control
- Defined detailed structs for all standard EVM opcodes (STOP, ADD, MUL, etc.)
- Implemented gas costs, stack requirements, and execution function signatures for each opcode
- Created a union type `Operation` to represent all possible opcodes
- Added `getOperation()` function to map bytecode values to their corresponding operations
- Updated the `Contract.getOp()` method to properly retrieve opcodes from bytecode
- Modified the program counter type from `u64` to `usize` for better memory addressing
The implementation follows the Ethereum Yellow Paper specifications for opcodes, their gas costs, and stack requirements. Each opcode struct …
> feat: Add opcodes

- .github/workflows/nx.yml
- build.zig
- src/Server/main.zig
- src/Server/middleware/Logger.zig
- src/Server/server.zig
Added a JSON-RPC server implementation to the ZigEVM project. This includes:
- Created a server module with HTTP request handling capabilities
- Implemented logging middleware for request tracking
- Added server tests to verify JSON-RPC functionality
- Set up build configuration for the server executable
- Added dedicated test steps for individual components (RLP, ABI, Compiler, etc.)
- Integrated httpz dependency for HTTP server functionality
The server listens on port 8546 and currently responds to JSON-RPC requests with a basic structure. This lays the groundwork for implementing actual EVM JSON-RPC methods.
- Added comprehensive server tests that verify HTTP request/response handling
- Updated CI workflow to run server tests
- Created individual test steps for each component to allow …
> feat: Add middleware and tests to server

- src/Server/middleware/Logger.zig
Updated the `Logger` middleware in the server to:
1. Accept a `Config` parameter in the `init` function
2. Add error handling to the `executor.next()` call
3. Define a new empty `Config` struct for configuration options
Tested that the server middleware chain properly propagates errors and that the Logger middleware initializes correctly with the new Config parameter.
> fix: Broken logger

- src/Utils/hex.zig
- src/Utils/keccak256.zig
- src/stdlib-loader.js
- src/wasm-loader.js
Renamed WASM-exported keccak256 functions by removing the `zig_` prefix to improve API consistency. Updated all corresponding function calls in JavaScript files to match the new function names.
Verified that all keccak256 function calls in JavaScript files were updated to use the new function names. Ensured that the function signatures and implementations remain unchanged to maintain compatibility.
> chore: Rename keccak256

- app/src-tauri/build.rs
- app/src-tauri/src/lib.rs
- build.zig
- src/Utils/keccak256.zig
- src/root.zig
Integrate Zig with Tauri by adding a build script that compiles the Zig EVM library and links it to the Rust application. This PR:
- Adds a `connect_zig()` function in `build.rs` to compile the Zig code and link the static library
- Exposes the Keccak256 hash function from Zig to Rust through FFI
- Updates the `greet` command to demonstrate the integration by computing the Keccak256 hash of the input name
- Refactors the Zig root module to export the Keccak256 function for FFI usage
- Verified the Zig compilation process works correctly across platforms
- Tested the FFI integration between Rust and Zig
- Confirmed the Keccak256 hash function produces correct results
> chore: Connect zig to tauri app

- pnpm-lock.yaml
Removed unused dependencies from `pnpm-lock.yaml`, including:
- `app` and its dependencies (`app-client`, `cornerstone`, `modulator`)
- MongoDB-related packages (`mongodb`, `mongoose`, `bson`, `kareem`, etc.)
- Other unused packages (`mime@4.0.7`, `uglify-js`, `optimist`, `wordwrap`, etc.)
This cleanup helps reduce the project's dependency footprint and potential security vulnerabilities from unused packages.
Verified that the removed dependencies are not referenced in any project files. Ensured the lock file remains valid and consistent with the project's actual dependencies.
> fix: outdated pnpm-lock.yaml

- src/evm/constants.zig
- src/evm/contract.zig
- src/evm/jump_table.zig
- src/evm/opcodes/arithmetic.zig
- src/evm/opcodes/bitwise.zig
- src/evm/opcodes/comparison.zig
- src/evm/opcodes/control.zig
- src/evm/opcodes/memory.zig
- src/evm/opcodes/stack.zig
- src/evm/opcodes/storage.zig
- src/evm/stack.zig
Removed `inline` attribute from utility functions in the EVM implementation to better allow compiler reduce binary size. This change affects functions in several modules including constants, contract, jump_table, memory opcodes, and stack operations. In Fast mode compiler will usually be smart enough toinline and the official docs warn against inlining for perf reasons
The code has been tested to ensure that removing the `inline` attribute doesn't affect functionality. Performance-critical paths have been verified to maintain their efficiency, as the compiler will still automatically inline functions where beneficial.
> 📦 perf: remove explicit inline keywords to reduce bundle size

- extensions/test-matchers/src/chainable/chainable.spec.ts
- extensions/test-matchers/src/chainable/chainable.ts
- extensions/test-matchers/src/chainable/chainable.type-spec.ts
- extensions/test-matchers/src/chainable/types.ts
- extensions/test-matchers/src/index.ts
See #1747 for full package overview and plan.
Add internal functions to make vitest matchers chainable using chai, to reproduce waffle chainable matchers `await expect(tx).toEmit(event).withArgs(args)` or such.
Includes full tests & type tests for chainable functionality.
> feat: @tevm/test-matchers - Chainable vitest matchers
