.gitmodules
plugins/solidity-resolver/src/index.ts
plugins/solidity-resolver/src/solc/solcPlugin.ts

:rotating_light: fix(ci): Fix linter

---

docs/introduction/get-started.md
examples/vite/.stackblitzrc

:sparkles: feat(vite): Add stackblitz

---

.stackblitzrc
docs/introduction/get-started.md
examples/vite/.stackblitzrc

:truck: chore(stackblitz): move stackblitz config to root for now

---

.stackblitzrc
docs/introduction/get-started.md
examples/vite/.stackblitzrc

:truck: feat(stackblitz): move config file to subfolder

---

docs/introduction/get-started.md
plugins/solidity-resolver/src/solc/solcPlugin.ts

:pencil2: fix(docs): Fix stackblitz link typo

---

tsconfig.json

:wrench: feat(tsconfig): module: esnext"

---

.github/workflows/build.yml

:construction_worker: feat: Add build github action

---

docs/reference/contract.md

:memo: feat(docs): Update the contract docs to the new api

---

docs-beta/.gitignore
docs-beta/.vitepress/config.ts
docs-beta/.vitepress/footer.ts
docs-beta/.vitepress/nav.ts
docs-beta/.vitepress/sidebar.ts
docs-beta/.vitepress/socialLinks.ts
docs-beta/.vitepress/theme/index.css
docs-beta/.vitepress/theme/index.ts
docs-beta/README.md
docs-beta/index.md
docs-beta/introduction/get-started.md
docs-beta/introduction/hello-world.md
docs-beta/introduction/installation.md
docs-beta/package.json
docs-beta/reference/.md
docs-beta/reference/read-contract.md
docs-beta/reference/wagmi.md
docs-beta/reference/write-contract.md
docs-beta/rome.json

Add docs-beta package to document the limited react API fore beta release
Currently doesn't build so not added to pnpm monorepo yet

:package: feat(monorepo): Add docs-beta package

---

docs-beta/.vitepress/sidebar.ts
docs-beta/introduction/hello-world.md
docs-beta/introduction/installation.md
docs-beta/package.json
docs-beta/reference/write-contract.md
pnpm-lock.yaml
pnpm-workspace.yaml
vercel.json

Make docs-beta the official docs site in anticipation of beta release.
- make it build correctly
- switch vercel to using docs-beta
Builds correctly

:construction_worker: feat(docs): Switch docs site to docs-beta

---

docs-beta/introduction/get-started.md

- Just spread into wagmi to remove need to install new library

:recycle: feat(docs-beta): Change spec to just spread into wagmi"

---

docs-beta/introduction/get-started.md

- fix open zepplen import
- exmplain why we commit deploy artifacts

:bug: fix(beta-docs): Fix issues with get-started

---

.github/actions/setup/action.yml
package.json
pnpm-lock.yaml

:arrow_up: feat(monorepo): Update pnpm to latest

---

docs-beta/.vitepress/sidebar.ts
docs-beta/index.md
docs-beta/introduction/get-started.md
docs-beta/introduction/installation.md

Minor cleanups to the introduction docs-beta

:pencil2: fix(docs-beta): Clean ups

---

docs-beta/.vitepress/sidebar.ts

:bug: fix(docs-beta): Fix sidebar

---

e2e/package.json
pnpm-lock.yaml

:arrow_up: chore: pnpm up --latest

---

docs-beta/index.md

Include reference on home page

:sparkles: feat(docs-beta): Add reference to home page

---

docs-beta/index.md

:pencil2: fix(docs-beta): Fix home page typos

---

config/.gitignore
config/CHANGELOG.md
config/LICENSE
config/README.md
config/package.json
config/rome.json
config/src/index.ts
config/tsconfig.json
config/tsup.config.ts
docs-beta/.vitepress/sidebar.ts
docs-beta/reference/config.md
examples/beta/evmts.config.ts
examples/beta/foundry.toml
examples/beta/package.json
examples/beta/src/App.tsx
pnpm-lock.yaml
pnpm-workspace.yaml

:package: feat(monorepo): Add new config package for evmts.config.ts

---

config/src/index.ts

:bug: fix(config): Fix template string typo

---

config/package.json
config/src/index.ts

:rotating_light: fix(config): Fix linter

---

config/package.json
config/src/index.ts
plugins/ts-plugin/src/decorators/getScriptSnapshot.ts

:bug: fix(ts-plugin): catch solc errors

---

config/package.json
config/src/index.ts
examples/beta/package.json
plugins/ts-plugin/src/decorators/getScriptSnapshot.ts
pnpm-lock.yaml

:arrow_up: upgrade solc to 8.20

---

config/package.json
config/src/index.ts
examples/beta/evmts.config.ts
examples/beta/foundry.toml
examples/beta/package.json
examples/beta/script/Deploy.s.sol
examples/beta/src/Counter.tsx
examples/beta/src/contracts/Counter.sol
examples/beta/test/Counter.t.sol
plugins/ts-plugin/src/decorators/getScriptSnapshot.ts
pnpm-lock.yaml

:sparkles: feat(example-beta) Add evmts config and contracts

---

plugins/contract/.gitignore
plugins/contract/CHANGELOG.md
plugins/contract/LICENSE
plugins/contract/README.md
plugins/contract/package.json
plugins/contract/rome.json
plugins/contract/src/index.ts
plugins/contract/tsconfig.json
plugins/contract/tsup.config.ts

:package: feat: Add contract package

---

examples/vite/package.json
plugins/solidity-resolver/src/foundry/foundryModules.ts
plugins/solidity-resolver/src/solc/solcPlugin.ts
plugins/solidity-resolver/src/types/SolidityResolver.ts
plugins/ts-plugin/src/decorators/getScriptSnapshot.spec.ts
pnpm-lock.yaml

:sparkles: fix(solidity-resolve): Resolve new module shape

---

examples/beta/package.json
examples/beta/src/App.tsx
examples/beta/src/Counter.tsx
pnpm-lock.yaml

:sparkles: feat(example-beta): Add readContract example

---

pnpm-lock.yaml

:wrench: fix(monorepo): update pnpm-lock.yaml

---

internal/contract/src/index.ts

:bug: fix(contract): Fix type error

---

examples/beta/package.json

:rotating_light: fix(bet): Fix package json linter

---

examples/beta/package.json
internal/contract/src/index.ts

:rotating_light: fix(contract): Fix linter

---

examples/beta/package.json
internal/contract/src/index.ts
internal/solidity-resolver/src/solc/solcPlugin.ts

:bug: fix(solidity-resolver): Fix type import

---

internal/solidity-resolver/src/solc/solcPlugin.ts

:bug: fix(solidity-resolver): Fix bug with unparsed json

---

examples/beta/src/Counter.tsx
internal/solidity-resolver/src/solc/solcPlugin.ts

:bug: fix(example-beta): Use read.count instead of count

---

lsp/ts-plugin/src/decorators/getScriptSnapshot.spec.ts

:white_check_mark: test(ts-plugin): update snapshot

---

README.md
examples/beta/package.json

:memo: docs: README.md refresh

---

docs-beta/getting-started/quick-start.md

:bug: fix(docs-beta): fix quick start stackblitz link

---

docs-beta/.vitepress/sidebar.ts

:sparkles: feat(docs-beta): Sidebar polish

---

docs-beta/.vitepress/sidebar.ts
docs-beta/ethers/overview.md
docs-beta/web3js/overview.md

:memo: feat(docs-beta): Add web3js overview

---

bundlers/rspack/.gitignore
bundlers/rspack/CHANGELOG.md
bundlers/rspack/LICENSE
bundlers/rspack/README.md
bundlers/rspack/package.json
bundlers/rspack/rome.json
bundlers/rspack/src/index.spec.ts
bundlers/rspack/src/index.ts
bundlers/rspack/tsconfig.json
bundlers/rspack/tsup.config.ts
pnpm-lock.yaml

:package: feat(bundlers): Add rspack plugin

---

bundlers/rspack/.gitignore
bundlers/rspack/CHANGELOG.md
bundlers/rspack/LICENSE
bundlers/rspack/README.md
bundlers/rspack/package.json
bundlers/rspack/rome.json
bundlers/rspack/src/index.spec.ts
bundlers/rspack/src/index.ts
bundlers/rspack/tsconfig.json
bundlers/rspack/tsup.config.ts
cli/.gitignore
cli/CHANGELOG.md
cli/LICENSE
cli/README.md
cli/package.json
cli/rome.json
cli/src/index.ts
cli/tsconfig.json
cli/tsup.config.ts
pnpm-lock.yaml
pnpm-workspace.yaml

:package: feat(cli): Add cli package

---

bundlers/README.md
bundlers/rspack/.gitignore
bundlers/rspack/CHANGELOG.md
bundlers/rspack/LICENSE
bundlers/rspack/README.md
bundlers/rspack/package.json
bundlers/rspack/rome.json
bundlers/rspack/src/index.spec.ts
bundlers/rspack/src/index.ts
bundlers/rspack/tsconfig.json
bundlers/rspack/tsup.config.ts
cli/.gitignore
cli/CHANGELOG.md
cli/LICENSE
cli/README.md
cli/package.json
cli/rome.json
cli/src/index.ts
cli/tsconfig.json
cli/tsup.config.ts
docs-beta/guides/next.md
docs-beta/guides/vite.md
docs-beta/guides/webpack.md
docs-beta/tutorial/configuration.md
lsp/README.md
pnpm-lock.yaml
pnpm-workspace.yaml

:memo: docs: readme refresh

---

.github/workflows/build.yml

:construction_worker: fix(ci): Fix typos in build github action

---

.github/workflows/lint.yml
.github/workflows/unit.yml

:construction_worker: feat(ci): Add workflow dispatch to all actions

---

.changeset/config.json
.github/workflows/lint.yml
.github/workflows/snapshot.yml
.github/workflows/unit.yml

:construction_worker: feat(ci): Add robust changeset action

---

.changeset/new-items-shout.md

Do a patch on all packages so snapshots start publishing

chore(npm): Add initial changeset for all packages

---

package.json
pnpm-lock.yaml

:heavy_plus_sign: fix(npm): pnpm i @changesets/changelog-github

---

.github/workflows/release.yml
package.json

:bug: feat(npm): Fix changeset:version script

---

.changeset/config.json
package.json

:wrench: chore: Change root name to evmts-monorepo

---

docs-beta/.vitepress/nav.ts

:bug: feat(docs-beta): Fix nav bar link

---

docs-beta/.vitepress/nav.ts
docs-beta/.vitepress/sidebar.ts

:coffin: chore(docs-beta): Hide unimplemented overview

---

.github/workflows/snapshot.yml

:construction_worker: feat(cd): Only release snapshot releases on workflow_dispatch

---

README.md
docs/contributing.md
docs/disclosures.md
docs/how-plugin-works.md
docs/introduction/get-started.md
docs/introduction/hello-world.md
docs/introduction/vite.md
docs/introduction/why.md
docs/monorepo.md

fix: typos

---

config/package.json
config/src/index.ts
pnpm-lock.yaml

:sparkles: feat(config): Load config

---

docs-beta/.vitepress/sidebar.ts
docs-beta/tutorial/overview.md
docs-beta/tutorial/setup.md

:bug: fix(docs-beta): Fix some dead links

---

bundlers/bundler/package.json
bundlers/esbuild-plugin/package.json
bundlers/rspack-plugin/package.json
bundlers/vite-plugin/package.json
bundlers/webpack-plugin/package.json
cli/package.json
config/package.json
core/package.json
package.json
pnpm-lock.yaml
prototype/rollup-plugin-legacy/package.json

:fire: chore(monorepo): remove unused scripts

---

.github/workflows/build.yml

:pencil2: fix(ci): Name typo

---

docs-beta/.vitepress/nav.ts

:sparkles: feat(docs-beta): Update nav

---

docs-beta/.vitepress/nav.ts
docs-beta/.vitepress/sidebar.ts
docs-beta/reference/evmts-contract.md
docs-beta/viem/overview.md
docs-beta/wagmi/overview.md
docs-beta/wagmi/use-contract-event.md
docs-beta/wagmi/use-contract-read.md

:memo: feat: Add runtime library apis

---

docs-beta/.vitepress/nav.ts
docs-beta/.vitepress/sidebar.ts
docs-beta/index.md
docs-beta/reference/evmts-contract.md
docs-beta/viem/overview.md
docs-beta/wagmi/overview.md
docs-beta/wagmi/use-contract-event.md
docs-beta/wagmi/use-contract-read.md
examples/beta/evmts.config.ts
examples/beta/src/ReadContract.tsx

:zap: feat: better landing page

---

docs-beta/wagmi/use-contract-read.md

:memo: feat(docs-beta): Add ReadContract example

---

bundlers/bundler/src/foundry/foundryModules.ts
bundlers/bundler/src/solc/solcPlugin.ts
examples/beta/evmts.config.ts
examples/beta/tsconfig.json
lsp/ts-plugin/src/decorators/getScriptSnapshot.spec.ts
lsp/ts-plugin/src/decorators/getScriptSnapshot.ts
lsp/ts-plugin/src/factories/config.spec.ts
lsp/ts-plugin/src/factories/config.ts

:sparkles: feat: Enable address resolution for lsp

---

bundlers/bundler/src/foundry/foundryModules.ts
core/package.json
core/src/contract/index.ts
examples/beta/src/ReadContract.tsx
pnpm-lock.yaml

:sparkles: feat: Abi type magic on read

---

lsp/language-server/package.json
lsp/vscode/package.json
pnpm-lock.yaml

:arrow_up: feat(lsp): pnpm up vscode and langauge-server

---

bundlers/bundler/src/solc/solcPlugin.ts
lsp/ts-plugin/src/decorators/getScriptSnapshot.spec.ts

:sparkles: feat(bundler): Bundle in etherscan links

---

bundlers/bundler/src/solc/solcPlugin.ts
config/src/index.ts
examples/beta/evmts.config.ts
lsp/ts-plugin/src/decorators/getScriptSnapshot.spec.ts

:sparkles: feat(config): Support configuring more than one address

---

core/src/contract/index.ts

:sparkles: feat(core): Add events to object

---

bundlers/bundler/src/solc/solcPlugin.ts
core/src/contract/index.ts
examples/beta/evmts.config.ts
examples/beta/src/ReadContract.tsx
examples/beta/tsconfig.json
lsp/ts-plugin/src/decorators/getScriptSnapshot.spec.ts

:sparkles: feat: Enable picking address based on chainId

---

docs-alpha/index.md

:sparkles: feat: Update landing page based on feedback

---

.github/workflows/prerelease.yml

:bug: fix: Add more permissions

---

.github/actions/setup/action.yml

Fix git shas which were uncommented

:construction_worker: fix: Fix git shas

---

.changeset/old-crews-divide.md
core/src/contract/contract.ts
examples/beta/src/ReadContract.tsx

Add lazy usage of EVMts contracts for useWrite

:sparkles: feat(core): Enable lazy writing via regular object spreads of the fn

---

.changeset/clean-ravens-sparkle.md
core/src/contract/contract.ts

Add humanReadableAbi to EVMtsContract

:sparkles: feat: Add humanReadableAbis

---

.devcontainer/devcontainer.json
.vscode/extensions.json

Add vite extension to devcontainer

:construction_worker: feat: Add vite extension to devcontainer

---

package.json

:fire: chore: Clean up package.json

---

nx.json
package.json
pnpm-lock.yaml

:wrench: chore: nx repair

---

.changeset/seven-jars-provide.md
core/package.json
core/src/contract/contract.spec.ts
core/src/contract/contract.ts

- Add basic tests for EVMts contract
- Fix missing types

:white_check_mark: test(core): Add some basic EVMtsContract tests

---

.changeset/big-flowers-fix.md
lsp/ts-plugin/src/utils/isRelativeSolidity.spec.ts
lsp/ts-plugin/src/utils/isRelativeSolidity.ts

Fix bug with relative paths starting with `../` not being correctly detected

:bug: fix(ts-plugin): Fix relative solidity detection

---

.changeset/lovely-pens-do.md
core/src/contract/contract.spec.ts
core/src/contract/contract.ts

Fix bug with wagmi types not liking empty arrays for args

:bug: fix(core): Fix args being empty bug

---

lsp/language-server/.gitignore
lsp/language-server/bin/evmts-language-server.js
lsp/language-server/package.json
lsp/language-server/rome.json
lsp/language-server/src/createSolidityService.ts
lsp/language-server/src/getSolidityLanguageModule.ts
lsp/language-server/src/languageServerPlugin.ts
lsp/language-server/src/nodeServer.ts
lsp/language-server/tsconfig.json
pnpm-lock.yaml

- Add rome as linter
- Change output dir to dist from out
- Add standard evmts package.json scripts

:recycle: chore: make language-server a standard package

---

lsp/language-server/bin/evmts-language-server.js
lsp/language-server/package.json
lsp/language-server/src/index.ts
lsp/language-server/src/nodeServer.ts
lsp/language-server/tsup.config.ts
lsp/vscode/scripts/build.js
pnpm-lock.yaml

:construction_worker: feat(language-server): Use tsup for build

---

lsp/language-server/bin/evmts-language-server.js
lsp/language-server/package.json
lsp/language-server/src/index.ts
lsp/language-server/src/nodeServer.ts
lsp/language-server/tsup.config.ts
lsp/ts-plugin/package.json
lsp/ts-plugin/tsconfig.build.json
lsp/ts-plugin/tsconfig.json
lsp/ts-plugin/tsup.config.ts
lsp/vscode/scripts/build.js
pnpm-lock.yaml

:construction_worker: feat(ts-plugin): Switch ts-plugin build to tsup

---

lsp/vscode/package.json
lsp/vscode/tsup.config.ts
pnpm-lock.yaml

Switch from using esbuild to tsup

:construction_worker: feat(vscode): Switch build to tsup

---

.github/workflows/e2e.yml
e2e/playwright.config.ts
e2e/src/pure.spec.ts

:white_check_mark: test: Update e2e test to beta example

---

bundlers/bundler/package.json
pnpm-lock.yaml

Fix bug where solc was not listed as a peer dependency

:bug: fix(bundlers): Fix bundler solc peer dep'

---

e2e/.env.example
e2e/.gitignore
e2e/package.json
e2e/playwright.config.ts
e2e/rome.json
e2e/src/fixtures.ts
e2e/src/pure.spec.ts
e2e/src/vite/WagmiEvents.spec.ts
pnpm-lock.yaml

Add synpress to run e2e tests with metamask
Runs synpress successfully locally but still a WIP

:white_check_mark: test(e2e): WIP add synpress

---

.changeset/chilly-steaks-unite.md
.changeset/spicy-buckets-eat.md

:bookmark: chore: Add changesets

---

.changeset/neat-crabs-kick.md
bundlers/bundler/package.json
bundlers/esbuild-plugin/package.json
bundlers/rollup-plugin/package.json
bundlers/rspack-plugin/package.json
bundlers/vite-plugin/package.json
bundlers/webpack-plugin/package.json
cli/package.json
config/package.json
core/package.json
lsp/ts-plugin/package.json

Fixed missing src folder in packages that would make types not be found

:bug: fix: Fix missing src folder in npm packages

---

docs-alpha/guides/vscode.md

:memo: docs: Update vscode docs

---

.github/workflows/prerelease.yml

Disable prerelease workflow as we are treating all 0.x versions of evmts as an alpha/beta

:construction_worker: chore: Disable prerelease workflow

---

README.md

:memo: docs: Add NEXT.js repo to top of docs

---

.github/workflows/formatter.yml

Seperate linter and formatters into their own build steps to run in parallel

:construction_worker: feat(ci): Seperate formatters into it's own ci step

---

.github/workflows/release.yml

Building was happening twice before releases

:construction_worker: fix(ci): Don't build twice on release

---

examples/next/package.json
examples/next/src/contracts/WagmiMintExample.sol
examples/next/tsconfig.json
pnpm-lock.yaml

:bug: fix(next-example): Use 0.8.19

---

examples/next/package.json
examples/next/src/contracts/WagmiMintExample.sol
examples/next/tsconfig.json
package.json
pnpm-lock.yaml

:construction_worker: fix: Skip nx cache when releasing

---

examples/next/package.json

:lipstick: fix: sort-package-json

---

.changeset/soft-lions-hug.md
.gitmodules
config/src/index.ts
examples/vite/src/contracts/WagmiMintExample.sol
examples/vite/tsconfig.json

Fix bug with foundry toml loading
Tested manually in vite app

:bug: fix(bundler): Fix foundry detection bug

---

.changeset/light-cooks-study.md
bundlers/bundler/package.json

:bug: fix: Fix bin doesn't exist error

---

examples/vite/rome.json

:wrench: fix: Add lib to vite ignore

---

.changeset/slimy-kings-brake.md
config/src/defineConfig.ts
config/src/loadConfig.ts
lsp/ts-plugin/src/factories/EVMtsConfigFactory.ts
lsp/ts-plugin/src/tsPlugin.spec.ts
lsp/ts-plugin/src/tsPlugin.ts
lsp/ts-plugin/src/utils/solidityModuleResolver.ts

closes #282
- Add support for BaseUrI in tsconfig to bundler and lsp
- Fix bug with importing from lib and node_modules in lsp

:bug: fix: Support baseUrl lib and node_module imports

---

.changeset/empty-rivers-poke.md
bundlers/bundler/src/solc/solcPlugin.ts
bundlers/bundler/src/utils/getEtherscanLinks.ts

Fix bugs with undefined etherscan links like devnet showing up as undefined

:bug: fix: Remove undefined etherscan links

---

.changeset/config.json

closes #295
Link package versions together for easier usage of evmts

:bookmark: chore: Link packages on changesets

---

.changeset/hot-jeans-jog.md
bundlers/bundler/package.json
bundlers/bundler/src/unplugin/index.ts
examples/next/src/contracts/WagmiMintExample.sol
examples/vite/src/contracts/WagmiMintExample.sol
pnpm-lock.yaml

Update all bundler deps to latest

:arrow_up: chore(bundler): pnpm up --latest

---

package.json
pnpm-lock.yaml

:arrow_up: chore: pnpm up nx

---

nx.json
package.json

npmScope is deprecated and some nx tools no longer work with it

:construction_worker: fix: Update deprecated npmScope in nx.json

---

bundlers/bundler/package.json
bundlers/bundler/src/index.ts
bundlers/bundler/src/solc/bundler.spec.ts
bundlers/bundler/src/solc/bundler.ts
bundlers/bundler/src/solc/compileContracts.spec.ts
bundlers/bundler/src/solc/index.ts
bundlers/bundler/src/solc/moduleFactory.spec.ts
bundlers/bundler/src/solc/moduleFactory.ts
bundlers/bundler/src/solc/resolveArtifacts.spec.ts
bundlers/bundler/src/solc/resolveImportPath.spec.ts
bundlers/bundler/src/solc/resolveImports.spec.ts
bundlers/bundler/src/types.ts
bundlers/bundler/src/unplugin/index.spec.ts
bundlers/bundler/src/unplugin/index.ts
bundlers/bundler/src/utils/formatPath.spec.ts
bundlers/bundler/src/utils/isImportLocal.spec.ts
bundlers/bundler/vitest.config.ts
lsp/ts-plugin/src/bin/evmts-gen.ts
lsp/ts-plugin/src/decorators/getScriptSnapshot.ts
pnpm-lock.yaml

Now that bundler is stabilizing add a full unit test suite

:white_check_mark: test(bundler): Add full unit test suite

---

bundlers/bundler/rome.json
bundlers/bundler/src/bundler.spec.ts
bundlers/bundler/src/bundler.ts
bundlers/bundler/src/index.ts
bundlers/bundler/src/solc/index.ts
bundlers/bundler/src/solc/resolveArtifacts.ts
bundlers/bundler/src/solc/resolveArtifactsSync.spec.ts
bundlers/bundler/src/solc/resolveArtifactsSync.ts
bundlers/bundler/src/unplugin.spec.ts
bundlers/bundler/src/unplugin.ts
bundlers/esbuild-plugin/src/index.ts
bundlers/rollup-plugin/src/index.ts
bundlers/rspack-plugin/src/index.ts
bundlers/vite-plugin/src/index.ts
bundlers/webpack-plugin/src/index.ts

Move bundler and unplugin exports to top level of folder

:recycle: chore: Refactor file structure of bundler

---

.changeset/yellow-trees-pay.md
core/package.json
pnpm-lock.yaml

Update all packages in evmts core

:arrow_up: chore(core): pnpm up --latest

---

lsp/ts-plugin/package.json
lsp/ts-plugin/src/decorators/resolveModuleNameLiterals.spec.ts
lsp/ts-plugin/src/utils/solidityModuleResolver.spec.ts
lsp/ts-plugin/src/utils/solidityModuleResolver.ts
lsp/ts-plugin/vitest.config.ts
pnpm-lock.yaml

Add complete test coverage to lsp

:white_check_mark: test(ts-plugin): Add complete test coverage to lsp

---

.github/workflows/coverage.yml

:test_tube: chore: Add package names to coverage reports

---

config/src/defineConfig.spec.ts
config/src/loadConfig.spec.ts
config/src/loadConfig.ts

- Increase test coverage for config package
- Remove unused function

:white_check_mark: test(config): Add 99%+ test coverage

---

bundlers/bundler/vitest.config.ts
config/src/defineConfig.spec.ts
config/src/loadConfig.spec.ts
config/src/loadConfig.ts
config/vitest.config.ts
core/vitest.config.ts
lsp/ts-plugin/vitest.config.ts

Add thresholds for test coverage

:test_tube: chore: Add coverage thresholds

---

bundlers/config/src/EVMtsConfig.ts
bundlers/config/src/defineConfig.ts
bundlers/config/src/handleDeprecations.spec.ts
bundlers/config/src/handleDeprecations.ts
bundlers/config/src/loadConfig.spec.ts

Description
Throw a warning and fix for user if they pass in a deprecated property

:safety_vest: fix(config): Throw an error if an unknown property is passed to config

---

.changeset/calm-walls-obey.md
.changeset/tender-glasses-visit.md
bundlers/config/src/EVMtsConfig.ts
bundlers/config/src/defineConfig.ts
bundlers/config/src/handleDeprecations.spec.ts
bundlers/config/src/handleDeprecations.ts
bundlers/config/src/loadConfig.spec.ts
bundlers/config/src/loadConfig.ts

Throw a friendly warning if deprecated properties are detected

:safety_vest: feat(config): Add deprecation warnings for deprecated properties

---

.changeset/popular-lizards-itch.md

:bookmark: fix: Fix changeset that mentioned breaking change

---

.github/workflows/coverage.yml

:construction_worker: chore: Add esbuild to coverage reporter

---

core/package.json
pnpm-lock.yaml

Rome was as prod dep on accident

:bug: fix: Move rome to devDeps

---

.changeset/dull-lemons-agree.md
core/.gitignore
core/package.json
core/tsconfig.json

Fix issue with abitype not being recognized via generating a .d.ts file

:bug: fix(core): Generate .d.ts file

---

.changeset/dull-lemons-agree.md
bundlers/config/src/defineConfig.ts
core/.gitignore
core/package.json
core/tsconfig.json

Fix bug where forge default libs get overwritten if lib is provided

:bug: fix(bundler): Fix issue with overwriting forge config

---

.changeset/lemon-poets-play.md
core/package.json

:bug: fix: remove incorrect peer deps

---

.changeset/brown-dancers-heal.md
core/package.json
pnpm-lock.yaml

:arrow_down: fix: Downgrade abitype

---

.changeset/rich-swans-fry.md
core/package.json
pnpm-lock.yaml

Abitype was not resolving when installed as node module. Fix by making abitype a peer dep

:bug: fix(core): Make viem and abitype peer deps

---

.changeset/lemon-impalas-wait.md
.changeset/rich-swans-fry.md
bundlers/config/package.json
core/package.json
pnpm-lock.yaml

:arrow_up: chore(config): pnpm up --latest

---

.changeset/breezy-apples-wave.md
.changeset/purple-ducks-melt.md
bundlers/bundler/package.json
bundlers/config/src/defineConfig.ts
lsp/ts-plugin/package.json
pnpm-lock.yaml

:arrow_up: chore(ts-plugin): pnpm up --latest

---

.changeset/breezy-apples-wave.md
.changeset/great-dots-grow.md
.changeset/purple-ducks-melt.md
bundlers/bundler/package.json
bundlers/config/src/defineConfig.ts
bundlers/esbuild-plugin/package.json
bundlers/rollup-plugin/package.json
bundlers/rspack-plugin/package.json
bundlers/vite-plugin/package.json
bundlers/webpack-plugin/package.json
lsp/ts-plugin/package.json
pnpm-lock.yaml

:arrow_up: chore(plugins): pnpm up --latest

---

.changeset/forty-kings-punch.md
bundlers/bundler/src/bundler.spec.ts
bundlers/bundler/src/bundler.ts
lsp/ts-plugin/src/decorators/getScriptSnapshot.spec.ts

Fix bug with passing in contractName instead of "contractName" into the generated code

:bug: fix(bundler): Fix bug with passing in correct name type

---

.changeset/blue-worms-check.md
bundlers/bundler/CHANGELOG.md
bundlers/bundler/README.md
bundlers/bundler/package.json
bundlers/bundler/src/bundler.spec.ts
bundlers/bundler/src/bundler.ts
bundlers/bundler/src/unplugin.spec.ts
lsp/ts-plugin/src/decorators/getScriptSnapshot.spec.ts

Fixed typo with EVMts -> Evmts

:bug: fix(bundler): Fix typo in Evmts EVMts contract name

---

.changeset/stupid-camels-double.md
bundlers/bundler/src/bundler.spec.ts
bundlers/bundler/src/bundler.ts
bundlers/bundler/src/solc/compileContracts.spec.ts
bundlers/bundler/src/solc/compileContracts.ts
bundlers/bundler/src/solc/resolveArtifacts.spec.ts
bundlers/bundler/src/solc/resolveArtifacts.ts
bundlers/bundler/src/solc/resolveArtifactsSync.spec.ts
bundlers/bundler/src/solc/resolveArtifactsSync.ts
bundlers/bundler/src/types.ts
bundlers/bundler/src/unplugin.spec.ts
bundlers/bundler/src/unplugin.ts
lsp/ts-plugin/src/bin/evmts-gen.ts
lsp/ts-plugin/src/decorators/getScriptSnapshot.ts

Watch entire dependency graph for reloads

:sparkles: feat(bundler): Handle watching entire module graph

---

core/rome.json

:wrench: fix(core): add types to rome.json ignore

---

.changeset/lucky-swans-reflect.md
bundlers/bundler/src/bundler.spec.ts
bundlers/bundler/src/bundler.ts
lsp/ts-plugin/src/decorators/getScriptSnapshot.spec.ts

Remove private exports that I accidentally left in from debugging. The bundler doesn't export them so it's confusing they are there.

:bug: fix(bundler): remove the private exports

---

bundlers/bundler/src/bundler.ts
bundlers/bundler/src/utils/checkSolcVersion.spec.ts
bundlers/bundler/src/utils/checkSolcVersion.ts

closes #355
Add a warning if user does not have correct version of solc installed.
Unit tests

:rotating_light: feat(bundler): Add warning if solc compiler is not configured correctly

---

bundlers/bundler/src/utils/checkSolcVersion.spec.ts
bundlers/bundler/src/utils/checkSolcVersion.ts

- Solc version pr was all wrong
- Fix it

:bug: fix: Typos in checkSolcVersion

---

bundlers/bundler/package.json
bundlers/bundler/src/bundler.spec.ts
bundlers/bundler/src/bundler.ts
lsp/ts-plugin/src/decorators/getScriptSnapshot.spec.ts
pnpm-lock.yaml

- Fix bug in bundlers dts generation
- Start adding a test to test this against a real typescript build
- test doesn't work yet but it is useful already for manually testing
- currently it just writes files to file system and you can inspect them with editor

:bug: fix(bundler): Fix bug in .d.ts file

---

.changeset/famous-kiwis-return.md
.changeset/stupid-camels-double.md

- Fix minor version bump to a patch bump
- Add missing changeset for https://github.com/evmts/evmts-monorepo/commit/e20128c8ea5b49c98eba197ed234e808335f7479

:bookmark: fix: changesets

---

bundlers/bundler/package.json
bundlers/config/package.json
bundlers/esbuild-plugin/package.json
bundlers/rollup-plugin/package.json
bundlers/rspack-plugin/package.json
bundlers/vite-plugin/package.json
bundlers/webpack-plugin/package.json
core/package.json
docs/package.json
e2e/package.json
examples/esbuild/package.json
examples/next/package.json
examples/vite/package.json
lsp/language-server/package.json
lsp/ts-plugin/package.json
lsp/vscode/package.json
package.json

Add contributor to package.json

:wrench: chore: Add contributors to package.json

---

bundlers/bundler/package.json
bundlers/config/package.json
bundlers/esbuild-plugin/package.json
bundlers/rollup-plugin/package.json
bundlers/rspack-plugin/package.json
bundlers/vite-plugin/package.json
bundlers/webpack-plugin/package.json
core/package.json
docs/package.json
e2e/package.json
examples/esbuild/package.json
examples/next/package.json
examples/vite/package.json
lsp/language-server/package.json
lsp/ts-plugin/package.json
lsp/vscode/package.json
package.json
vercel.json

Fix vercel docs build that broke from seemingly nx changing behavior
Nx should be recognizing `docs` as `@evmts/docs` but isn't atm
Debug nx later time

:construction_worker: fix: Fix vercel docs build

---

.github/workflows/coverage.yml
pnpm-lock.yaml
runtime/ethers/.gitignore
runtime/ethers/CHANGELOG.md
runtime/ethers/LICENSE
runtime/ethers/README.md
runtime/ethers/package.json
runtime/ethers/rome.json
runtime/ethers/src/index.spec.ts
runtime/ethers/src/index.ts
runtime/ethers/tsconfig.json
runtime/ethers/tsup.config.ts
runtime/ethers/vitest.config.ts

Init ethers package to provide typesafe evmts contracts for ethers
Having a tough time even getting a hello world up and running atm
None just init

:package: chore: init ethers package

---

.changeset/grumpy-pianos-fry.md
.changeset/stale-peaches-smoke.md
runtime/core/package.json
runtime/core/src/event/eventFactory.spec.ts
runtime/core/src/read/readFactory.spec.ts
runtime/core/src/read/readFactory.ts
runtime/core/src/write/writeFactory.spec.ts
runtime/core/vitest.config.ts

- Bump min test coverage to 100 100 100 100
Lots

:white_check_mark: test(core): Add 100% test coverage

---

.changeset/old-vans-punch.md
.github/workflows/coverage.yml
bundlers/bundler/package.json
bundlers/bundler/src/bundler.spec.ts
bundlers/bundler/src/bundler.ts
bundlers/bundler/src/runtime/__snapshots__/generateEvmtsBody.spec.ts.snap
bundlers/bundler/src/runtime/generateEvmtsBody.spec.ts
bundlers/bundler/src/runtime/generateEvmtsBody.ts
bundlers/bundler/src/runtime/generateEvmtsBodyDts.spec.ts
bundlers/bundler/src/runtime/generateEvmtsBodyDts.ts
bundlers/bundler/src/runtime/generateRuntime.ts
bundlers/bundler/src/runtime/generateRuntimeSync.ts
bundlers/bundler/src/solc/compileContracts.spec.ts
bundlers/bundler/src/solc/moduleFactory.spec.ts
bundlers/bundler/src/solc/resolveArtifactsSync.spec.ts
bundlers/bundler/src/solc/resolveImports.spec.ts
bundlers/bundler/src/solc/resolveImports.ts
bundlers/bundler/src/unplugin.spec.ts
bundlers/bundler/src/unplugin.ts
bundlers/bundler/vitest.config.ts

- add 100% testing to bundler
- decompose bundler into more DRY pieces
- not sure what the missing branches coverage is on dts function
lots

:white_check_mark: test: Add 100% test coverage to bundler

---

package.json

Add coverage to pnpm all so it fails if coverage is not up to min

:wrench: chore: Change pnpm all to run coverage

---

nx.json
package.json

More granular filegroups for nx.json

:construction_worker: chore: Improve nx.json

---

.changeset/olive-taxis-tell.md
README.md
bundlers/README.md
bundlers/bundler/README.md
bundlers/config/package.json
bundlers/config/src/Config.ts
bundlers/config/src/EVMtsConfig.ts
bundlers/config/src/defineConfig.spec.ts
bundlers/config/src/defineConfig.ts
bundlers/config/src/expandEnv.spec.ts
bundlers/config/src/expandEnv.ts
bundlers/config/src/handleDeprecations.spec.ts
bundlers/config/src/handleDeprecations.ts
bundlers/config/src/index.ts
bundlers/config/src/loadConfig.spec.ts
bundlers/config/src/loadConfig.ts
bundlers/config/src/zodUtils.spec.ts
bundlers/config/src/zodUtils.ts
e2e/README.md
examples/README.md
lsp/README.md
lsp/ts-plugin/src/tsPlugin.spec.ts
nx.json
package.json
runtime/README.md

Add ability to add $FOO to tsconfig.json so we can support $ETHERSCAN_API_KEY
In future when we move to evmts.config.ts this will be removed
Unit tests

:sparkles: feat(config): Add ability to expand ENV variables in config

---

.changeset/angry-trains-argue.md
.changeset/olive-taxis-tell.md
README.md
bundlers/README.md
bundlers/bundler/README.md
bundlers/bundler/src/unplugin.ts
bundlers/config/package.json
bundlers/config/src/Config.ts
bundlers/config/src/EVMtsConfig.ts
bundlers/config/src/defineConfig.spec.ts
bundlers/config/src/defineConfig.ts
bundlers/config/src/expandEnv.spec.ts
bundlers/config/src/expandEnv.ts
bundlers/config/src/handleDeprecations.spec.ts
bundlers/config/src/handleDeprecations.ts
bundlers/config/src/index.ts
bundlers/config/src/loadConfig.spec.ts
bundlers/config/src/loadConfig.ts
bundlers/config/src/zodUtils.spec.ts
bundlers/config/src/zodUtils.ts
e2e/README.md
examples/README.md
lsp/README.md
lsp/ts-plugin/src/tsPlugin.spec.ts
nx.json
package.json
runtime/README.md

Type error was falsely marked as required though it defaults to {}

:bug: fix(plugins): Fix type error of config being falsely marked as required

---

bundlers/bundler/src/unplugin.ts

:mute: fix: Remove console.logs

---

.changeset/odd-ligers-search.md
bundlers/config/src/Config.ts
bundlers/config/src/defineConfig.spec.ts
bundlers/config/src/getDefaultSolcVersion.spec.ts
bundlers/config/src/getDefaultSolcVersion.ts
bundlers/config/src/loadConfig.spec.ts
bundlers/config/vitest.config.ts
examples/next/tsconfig.json
nx.json

:construction_worker: fix: typo in nx.json filegroup

---

.changeset/smooth-cups-rest.md
nx.json
pnpm-lock.yaml
runtime/core/package.json

Handle vitepress build output folder not matching other packages

:wrench: fix: docs page caching

---

.changeset/four-pens-hug.md

:bookmark: fix: changeset

---

.changeset/chatty-apes-flash.md

:bookmark: fix: Add missing changeset

---

runtime/ethers/src/createEthersContract.ts

Update ethers package with minor cleanups and better jsdoc comments and generics

:memo: feat(ethers): Add jsdoc comments

---

package.json
pnpm-lock.yaml
vitest.workspace.json

Allow vitest to run tests for the entire monorepo via a root level vitest config file

:construction_worker: chore: Add workspace vitest config

---

examples/esbuild/tsconfig.json

:fire: fix: Remove unused tsconfig input

---

.changeset/weak-toes-explain.md
bundlers/config/src/loadConfig.ts

Was swallowing error whenever tsconfig detection failed

:loud_sound: fix(config): Log error if tsconfig is missing

---

runtime/ethers/src/createEthersContract.spec.ts
runtime/ethers/src/createEthersContract.ts

Harden ethers contract code with some extra validation for the inputs

:safety_vest: fix(ethers): Add some extra defensive code for invalid configuration

---

.changeset/cuddly-shoes-attend.md
bundlers/config/src/Config.ts
bundlers/config/src/defineConfig.spec.ts
bundlers/config/src/defineConfig.ts
bundlers/config/src/loadConfig.spec.ts
bundlers/config/src/loadConfig.ts
bundlers/config/src/zodUtils.ts
bundlers/config/vitest.config.ts
examples/next/tsconfig.json
lsp/ts-plugin/src/decorators/getScriptKind.spec.ts
lsp/ts-plugin/src/decorators/getScriptSnapshot.spec.ts
lsp/ts-plugin/src/decorators/resolveModuleNameLiterals.spec.ts
lsp/ts-plugin/src/factories/decorator.spec.ts
lsp/ts-plugin/vitest.config.ts
runtime/core/src/event/eventFactory.spec.ts
runtime/core/src/evmtsContractFactory.spec.ts
runtime/core/src/evmtsContractFactory.ts
runtime/core/src/read/readFactory.spec.ts
runtime/core/src/write/writeFactory.spec.ts
runtime/ethers/src/createEthersContract.ts

Add some defensive validation for valid addresses

:safety_vest: feat: Add extra validation to evmtsContractFactory for invalid addresses

---

.changeset/poor-pumas-draw.md
.github/workflows/test.yml
bundlers/esbuild-plugin/package.json
bundlers/esbuild-plugin/src/index.spec.ts
bundlers/esbuild-plugin/vitest.config.ts
pnpm-lock.yaml

Add testing for esbuild plugin package

:white_check_mark: test: Add unit test to esbuild plugin

---

ethers/src/createEthersContract.spec.ts

Test is flaky because it was running against latest block instead of a pinned block tag/number

:test_tube: fix(ethers): fix flaky unit test

---

.changeset/violet-shrimps-camp.md
bundlers/bundler/src/solc/compileContracts.ts
bundlers/bundler/src/solc/moduleFactory.ts
bundlers/bundler/src/utils/invariant.spec.ts
bundlers/bundler/src/utils/invariant.ts
bundlers/bundler/vitest.config.ts

Fix bug where a recursive function was causing bundler to fail when import graph was deep

:bug: fix(bundler): Remove another recursive function for an iterative approach

---

.changeset/purple-rabbits-sell.md
bundlers/bundler/src/unplugin.spec.ts
bundlers/bundler/src/unplugin.ts
bundlers/bundler/vitest.config.ts

Add support for monorepos and node_module imports for the EVMts bundler

:bug: fix(bundler): Add monorepo support

---

.changeset/eight-games-watch.md
pnpm-lock.yaml
ts-plugin/package.json

Fix bug where solc wasn't correctly being declared as a peer dependency of ts-plugin

:bug: fix: Add solc as a peer dependency for ts-plugin

---

.changeset/chatty-apes-flash.md
.changeset/cuddly-shoes-attend.md
.changeset/few-pens-relax.md
.changeset/green-tables-develop.md
.changeset/poor-pumas-draw.md
.changeset/serious-shrimps-shave.md
.changeset/violet-camels-worry.md
.changeset/violet-shrimps-camp.md
.changeset/weak-toes-explain.md

Update changelog to more descriptive changelog.
Specifically include full usage instructions for ethers.js

:bookmark: version: Update changesets to a better more descriptive changelogs

---

ethers/README.md

Copy the changelog docs into README.md

:memo: docs: Update @evmts/ethers README.md

---

.changeset/gold-seals-buy.md
tsconfig/package.json

EVMts 0.7.0 is broken from evmts config not being public

:bug: fix(tsconfig): Make @evmts/tsconfig public

---

.changeset/thick-otters-march.md
cli/package.json
pnpm-lock.yaml

Update deps. Doing this to make the nx cache reset since 0.7.1 doesn't have a dist folder for some reason

:arrow_up: chore(cli): Update deps

---

.github/dependabot.yml

👷 chore: Update dependabot.yml

---

.changeset/dry-glasses-cheat.md
bundlers/bundler/src/runtime/generateEvmtsBody.spec.ts
bundlers/bundler/src/runtime/generateEvmtsBody.ts
bundlers/bundler/src/runtime/generateEvmtsBodyDts.spec.ts
bundlers/bundler/src/runtime/generateEvmtsBodyDts.ts
bundlers/bundler/src/runtime/generateRuntimeSync.spec.ts
bundlers/bundler/src/solc/resolveArtifacts.spec.ts
bundlers/bundler/src/solc/resolveArtifacts.ts
bundlers/bundler/src/solc/resolveArtifactsSync.spec.ts
bundlers/bundler/src/solc/resolveArtifactsSync.ts
bundlers/bundler/src/solc/solc.ts
bundlers/bundler/vitest.config.ts
cli/src/commands/generate/generate.ts
examples/vite/src/contracts/WagmiMintExample.sol

:sparkles: feat(bundler): Add natspec comments to bundled code

---

.changeset/friendly-cooks-juggle.md
bundlers/bundler/src/solc/compileContracts.spec.ts
bundlers/bundler/src/solc/compileContracts.ts

- Updates #438
- Update changeset
- Remove AST as it's currently unused until #440

:zap: feat: Update peformance increase in #438

---

.changeset/ten-pears-own.md
bundlers/bundler/package.json
bundlers/bundler/src/bundler.spec.ts
bundlers/bundler/src/bundler.ts
bundlers/bundler/src/solc/compileContracts.spec.ts
bundlers/bundler/src/solc/compileContracts.ts
bundlers/bundler/src/solc/resolveArtifacts.spec.ts
bundlers/bundler/src/solc/resolveArtifacts.ts
bundlers/bundler/src/solc/resolveArtifactsSync.spec.ts
bundlers/bundler/src/solc/resolveArtifactsSync.ts
bundlers/bundler/src/types.ts
bundlers/bundler/src/unplugin.ts
bundlers/bundler/vitest.config.ts
config/src/Config.ts
pnpm-lock.yaml
ts-plugin/src/bin/evmts-gen.ts
ts-plugin/src/decorators/getScriptSnapshot.ts

Add support for ast to EVMts
This unblocks being able to go-to-definition directly to the function definition

:sparkles: feat: Add ast support

---

.changeset/nervous-bugs-swim.md

Package that got deleted had a changeset breaking release

:fire: fix: Remove dead changeset

---

bundlers/bundler/src/bundler.spec.ts

Add better testing via adding new output types

:white_check_mark: test: Add better testing for bundler changes

---

.gitmodules

First step of #448
Adds revm as git submodule to repo

:package: chore: Add revm to repo

---

.changeset/dry-glasses-cheat.md
.changeset/friendly-cooks-juggle.md
.changeset/great-ads-nail.md
.changeset/modern-phones-think.md
.changeset/nervous-bugs-swim.md
.changeset/ten-pears-own.md
.changeset/wet-actors-cough.md

🏷️ chore: Update changesets

---

.github/workflows/snapshot.yml

Fix bugs with snapshot release

:bug: fix: Fix snapshot release

---

.gitmodules
README.md
rome.json

- Adds scaffold eth as a submodule to evmts monorepo

:package: feat: Add scaffold-evmts submodule

---

.changeset/silent-flies-check.md
config/package.json
config/src/loadConfig.spec.ts
config/src/loadConfig.ts
pnpm-lock.yaml

Fixed bug with evmts failing to load JSONc (JSON with comments). Previously if a tsconfig had comments in it or trailign commas json parsing would failing. Now EVMts will load these jsons correctly via using node-jsonc-parser instead of JSON.parse

:bug: fix(config): Enable JSONc parsing

---

.changeset/long-cheetahs-act.md
.changeset/real-days-obey.md
.github/workflows/test.yml
bundlers/bun/.gitignore
bundlers/bun/LICENSE
bundlers/bun/README.md
bundlers/bun/package.json
bundlers/bun/rome.json
bundlers/bun/src/index.spec.ts
bundlers/bun/src/index.ts
bundlers/bun/tsconfig.json
bundlers/bun/tsup.config.ts
bundlers/bun/vitest.config.ts
examples/bun/.gitignore
examples/bun/ExampleContract.sol
examples/bun/README.md
examples/bun/bunfig.toml
examples/bun/package.json
examples/bun/plugins.ts
examples/bun/pnpm-lock.yaml
examples/bun/readContract.spec.ts
examples/bun/readContract.ts
examples/bun/tsconfig.json
package.json
pnpm-lock.yaml

Added support for bun to EVMts
100% unit test coverage for `@evmts/plugin-bun`
unit test in example app running `bun test` testing the plugin e2e

:sparkles: feat: Add bun support

---

README.md
ethers/README.md

:memo: docs: Add bun starter to README.md

---

.changeset/famous-ravens-tease.md
cli/src/cli.ts
cli/src/commands/install/index.ts
cli/src/commands/install/install.ts
docs/ethers/overview.md

Add install command. Running install will install contracts from etherscan into the config and automatically generate

:sparkles: feat(cli): Add install command

---

.changeset/thin-fans-wink.md
ts-plugin/src/utils/solidityModuleResolver.ts
ts-plugin/vitest.config.ts

Add support for monorepo imports to the ts language server

:bug: fix(ts-plugin): Handle monorepos in lsp

---

docs/ethers/overview.md

Broken link from recent pr bad rebase

:bug: fix(docs): Broken build from broken link

---

core/tsconfig.json
tsconfig/base.json

Update tsconfig to a more modern module setting

:wrench: chore: Update tsconfig

---

.changeset/calm-ads-burn.md
bundlers/bun/src/index.spec.ts
bundlers/bun/src/index.ts
bundlers/bundler/package.json
bundlers/bundler/src/unplugin.spec.ts
bundlers/bundler/src/unplugin.ts
bundlers/bundler/src/utils/resolvePromise.spec.ts
config/package.json
config/src/fileExists.spec.ts
config/src/fileExists.ts
config/src/index.ts
config/src/loadConfig.ts
config/src/loadConfigAsync.spec.ts
config/src/loadConfigAsync.ts
config/tsconfig.json
config/vitest.config.ts

Improve startup time peformance by loading configs async

:zap: feat: Make config loading in bundlers async

---

.changeset/config.json

Ignore example app from npm publishing

:bug: fix(examples): remove svelte-ethers from changeset publishing

---

.changeset/cyan-trainers-change.md
ethers/src/Contract.spec.ts
ethers/src/TypesafeEthersContract.ts

:sparkles: feat(ethers): Make events typesafe

---

.changeset/selfish-zebras-think.md
ethers/src/createEthersContract.ts

Fix bugs and add missing features to the evmts version of the ethers contract. We simply forgot to make this change to reuse the new Contract class

:bug: fix(ethers): Update evmts version of ethers contract

---

.changeset/lazy-dingos-repair.md
core/src/write/Write.ts

Fixed bug with bad type in evmts-core

:bug: fix(core): Fix bug with Write type being wrong

---

core/package.json

Fix a stale path in package.json

:bug: fix(core): fix github path in package.json

---

core/src/event/Event.ts
core/src/read/Read.ts
core/src/write/Write.ts
examples/esbuild/src/constants.ts
examples/esbuild/src/ownerOf.spec.ts

:rotating_light: fix: Run linter

---

.changeset/calm-flowers-breathe.md
blockexplorer/README.md
docs/reference/blockexplorer/README.md
docs/reference/blockexplorer/classes/SafeStandardBlockExplorer.md
docs/reference/blockexplorer/classes/StandardBlockExplorer.md
docs/reference/blockexplorer/interfaces/BlockExplorerOptions.md
docs/reference/schemas/modules/evmts.md
docs/reference/state/.nojekyll
docs/reference/state/README.md
docs/reference/state/classes/AppState.md
docs/reference/state/classes/BaseState.md
docs/reference/state/interfaces/BaseStateOptions.md
docs/reference/state/modules.md
package.json
pnpm-lock.yaml
pnpm-workspace.yaml
state/.gitignore
state/LICENSE
state/README.md
state/package.json
state/rome.json
state/src/AppState.ts
state/src/BaseState.spec.ts
state/src/BaseState.ts
state/src/index.js
state/tsconfig.json
state/tsup.config.ts
state/typedoc.json
state/vitest.config.ts

Init new state package for handling evmts state with zustand. Do this one in TS because JS is painful for state
Starts #524

:package: feat: Init new state package

---

blockexplorer/package.json
blockexplorer/typedoc.json
bundlers/bundler/typedoc.json
docs/reference/blockexplorer/classes/SafeStandardBlockExplorer.md
docs/reference/blockexplorer/classes/StandardBlockExplorer.md
docs/reference/blockexplorer/interfaces/BlockExplorerOptions.md
docs/reference/blockexplorer/modules.md
schemas/package.json
schemas/typedoc.json

Update docs to only use typedoc.json

:construction_worker: chore: Update docs to use typedoc.json only

---

.github/workflows/docs.yml
nx.json
revm/package.json

Fail ci if docs are not up to date

:construction_worker: chore: Add ci check for docs being up to date

---

.github/workflows/docs.yml
README.md
nx.json
revm/package.json

Clear docs with message about EVMts beta

:memo: docs: Update readme for evmts beta

---

bundlers/bun/typedoc.json
bundlers/esbuild/typedoc.json
bundlers/rollup/typedoc.json
bundlers/rspack/typedoc.json
bundlers/vite/typedoc.json
bundlers/webpack/typedoc.json
docs/reference/bun-plugin/.nojekyll
docs/reference/bun-plugin/README.md
docs/reference/bun-plugin/modules.md
docs/reference/esbuild-plugin/.nojekyll
docs/reference/esbuild-plugin/README.md
docs/reference/esbuild-plugin/modules.md
docs/reference/rollup-plugin/.nojekyll
docs/reference/rollup-plugin/README.md
docs/reference/rollup-plugin/modules.md
docs/reference/rspack-plugin/.nojekyll
docs/reference/rspack-plugin/README.md
docs/reference/rspack-plugin/modules.md
docs/reference/vite-plugin/.nojekyll
docs/reference/vite-plugin/README.md
docs/reference/vite-plugin/modules.md
docs/reference/webpack-plugin/.nojekyll
docs/reference/webpack-plugin/README.md
docs/reference/webpack-plugin/modules.md

Docs were committed on accident

:recycle: chore: Remove docs that were committed on accident

---

.changeset/lovely-carrots-tie.md
bundlers/bun/typedoc.json
bundlers/esbuild/src/index.spec.ts
bundlers/esbuild/tsconfig.json
bundlers/esbuild/typedoc.json
bundlers/rollup/typedoc.json
bundlers/rspack/typedoc.json
bundlers/vite/typedoc.json
bundlers/webpack/typedoc.json
docs/reference/bun-plugin/.nojekyll
docs/reference/bun-plugin/README.md
docs/reference/bun-plugin/modules.md
docs/reference/esbuild-plugin/.nojekyll
docs/reference/esbuild-plugin/README.md
docs/reference/esbuild-plugin/modules.md
docs/reference/rollup-plugin/.nojekyll
docs/reference/rollup-plugin/README.md
docs/reference/rollup-plugin/modules.md
docs/reference/rspack-plugin/.nojekyll
docs/reference/rspack-plugin/README.md
docs/reference/rspack-plugin/modules.md
docs/reference/vite-plugin/.nojekyll
docs/reference/vite-plugin/README.md
docs/reference/vite-plugin/modules.md
docs/reference/webpack-plugin/.nojekyll
docs/reference/webpack-plugin/README.md
docs/reference/webpack-plugin/modules.md

Migrate esbuild-plugin to NodeNext

:recycle: chore(esbuild-plugin): Migrate esbuild-plugin to NodeNext

---

.changeset/chilly-trees-explain.md
.changeset/lovely-carrots-tie.md
bundlers/bun/typedoc.json
bundlers/esbuild/src/index.spec.ts
bundlers/esbuild/tsconfig.json
bundlers/esbuild/typedoc.json
bundlers/rollup/tsconfig.json
bundlers/rollup/typedoc.json
bundlers/rspack/typedoc.json
bundlers/vite/typedoc.json
bundlers/webpack/typedoc.json
docs/reference/bun-plugin/.nojekyll
docs/reference/bun-plugin/README.md
docs/reference/bun-plugin/modules.md
docs/reference/esbuild-plugin/.nojekyll
docs/reference/esbuild-plugin/README.md
docs/reference/esbuild-plugin/modules.md
docs/reference/rollup-plugin/.nojekyll
docs/reference/rollup-plugin/README.md
docs/reference/rollup-plugin/modules.md
docs/reference/rspack-plugin/.nojekyll
docs/reference/rspack-plugin/README.md
docs/reference/rspack-plugin/modules.md
docs/reference/vite-plugin/.nojekyll
docs/reference/vite-plugin/README.md
docs/reference/vite-plugin/modules.md
docs/reference/webpack-plugin/.nojekyll
docs/reference/webpack-plugin/README.md
docs/reference/webpack-plugin/modules.md

Migrate RollupPlugin to node next

:recycle: feat: Migrate rollup plugin to NodeNext

---

.changeset/stale-avocados-fail.md
bundlers/rspack/tsconfig.json

Migrate RSPack plugin to node next

:recycle: chore(rspack-plugin): Migrate rspack plugin to NodeNext

---

.changeset/seven-bees-film.md
.changeset/stale-avocados-fail.md
bundlers/rspack/tsconfig.json
bundlers/vite/tsconfig.json

Migrate vite plugin to NodeNext

:recycle: chore(vite-plugin): Migrate vite plugin to NodeNext

---

.changeset/proud-panthers-build.md
.changeset/seven-bees-film.md
.changeset/stale-avocados-fail.md
bundlers/rspack/tsconfig.json
bundlers/vite/tsconfig.json
bundlers/webpack/tsconfig.json

Migrate webpack plugin to NodeNext

:recycle: chore(webpack-plugin): Migrate webpack plugin to NodeNext

---

bundlers/bundler/src/index.js

Don't export types in .js file

:bug: fix(bundler): Don't export types file

---

bundlers/bun/src/index.js
bundlers/bundler/src/createCache.d.ts
bundlers/bundler/src/index.js

Explictly export apis
https://github.com/evmts/evmts-monorepo/issues/586

:recycle: chore(bun-plugin): Explocitly export the public api

---

blockexplorer/package.json
bundlers/bun/package.json
bundlers/bun/src/bunFile.js
bundlers/bundler/package.json
bundlers/bundler/src/unplugin.js
bundlers/esbuild/package.json
bundlers/rollup/README.md
bundlers/rollup/package.json
bundlers/rspack/package.json
bundlers/vite/README.md
bundlers/vite/package.json
bundlers/webpack/package.json
config/package.json
config/src/loadConfig.js
core/package.json
docs/reference/bundler/modules/unplugin.md
docs/reference/config/modules.md
docs/reference/rollup-plugin/README.md
docs/reference/vite-plugin/README.md
ethers/package.json
examples/esbuild/build.js
examples/esbuild/package.json
examples/esbuild/src/index.js
revm/package.json
schemas/package.json
state/package.json
ts-plugin/package.json

Fix exports field in package.json

:wrench: chore: Fix package.json exports

---

blockexplorer/package.json
bundlers/bun/package.json
bundlers/bun/src/bunFile.js
bundlers/bundler/package.json
bundlers/bundler/src/unplugin.js
bundlers/esbuild/package.json
bundlers/rollup/README.md
bundlers/rollup/package.json
bundlers/rspack/package.json
bundlers/vite/README.md
bundlers/vite/package.json
bundlers/webpack/package.json
config/package.json
config/src/loadConfig.js
core/package.json
docs/reference/bundler/modules/unplugin.md
docs/reference/config/modules.md
docs/reference/rollup-plugin/README.md
docs/reference/vite-plugin/README.md
ethers/package.json
examples/esbuild/build.js
examples/esbuild/package.json
examples/esbuild/src/index.js
package.json
revm/package.json
schemas/package.json
state/package.json
ts-plugin/package.json

:wrench: fix: Fix package.jsons cript

---

.github/workflows/fixtures.yml

Add a ci check that runs the fixtures and makes sure they passes. This adds yet another layer of testing and validates the dev watch mode commands work

:white_check_mark: test: Add fixtures to ci

---

.github/workflows/fixtures.yml
config/src/loadConfig.js

:bug: fix(config): Copy pasta

---

CONTRIBUTING.md
README.md

:memo: docs: Add getting started docs for CONTRIBUTING.md

---

.github/workflows/test.yml

Add @evmts/effect to code coverage reporting

:construction_worker: chore: Add @evmts/effect to code coverage reporting

---

.github/workflows/snapshot.yml

:construction_worker: chore: Disable snapshots automatically publishing

---

.github/actions/setup/action.yml
.github/workflows/test.yml
blockexplorer/package.json
bundlers/bun/package.json
bundlers/bundler/package.json
bundlers/esbuild/package.json
bundlers/rollup/package.json
bundlers/rspack/package.json
bundlers/unplugin/package.json
bundlers/vite/package.json
bundlers/webpack/package.json
config/package.json
core/package.json
effect/package.json
ethers/package.json
experimental/solc/package.json
resolutions/package.json
runtime/package.json
schemas/package.json
solc/package.json
state/package.json
ts-plugin/package.json

Add declaration maps to type builds so go-to-definition takes folks to the source code

:sparkles: feat: Add declaration maps to type build

---

.changeset/pink-keys-add.md

Add missing changeset for https://github.com/evmts/evmts-monorepo/pull/610

:bookmark: chore: Changeset

---

.github/workflows/test.yml
config/package.json
config/src/loadConfig.spec.ts
config/vitest.config.ts

:white_check_mark: test: Fix config test

---

.github/FUNDING.yml

💲 Create FUNDING.yml

---

.github/actions/setup/action.yml

:arrow_up: Chore: Bump bun version to 1.08

---

.github/actions/setup/action.yml

Remove frozen lockfile because bun behaving differently in CI and locally is wasting too much time

:poop: Feat: Remove --frozen-lockfile

---

package.json

Fix sort-package-json so it doesn't sort node_modules/* and lib/*

:bug: Fix: sort-package-json

---

CONTRIBUTING.md
README.md

Forgot to include submodules in getting started

:memo: Fix: Update contributing getting started

---

packages/evmts/src/evmts.spec.ts

:white_check_mark: Test: Add test for runCall

---

packages/evmts/package.json
packages/evmts/src/evmts.spec.ts

:white_check_mark: Feat(evmts): Add test coverage

---

docs/homepage.html

Add new docs homepage
- Code example on right
- Important information on left
Short overview of the features
More in depth explanation of the main feature with a demo
SHould show a gif of using the LSP in vscode
Live code example of foundry scripting
Screenshot of the devtools
- Star on github
- Getting started
- Stack blitz

:lipstick: Feat: Start adding new docs page homepage

---

vm/.gitignore
vm/tsconfig.json

:bug: Fix(vm): Fix type generation

---

.github/workflows/prerelease.yml

:bug: Fix: Fix copy pasta in prerelease workflow

---

.changeset/config.json

Changesets were failing because a package that got removed was included

:bug: Fix: Remove e2e from changeset ignore

---

.changeset/rich-turkeys-relate.md

Package name changed which broke the changeset workflow

:bug: Fix: Update broken changeset

---

.github/workflows/release.yml

Since EVMts is doing prereleases now we want the normal releases to be on a seperate branch than main

:construction_worker: Chore: Change release branch to v1

---

vm/src/actions/runCall.ts
vm/src/evmts.spec.ts

Add test to help debug issue in https://github.com/0xNonCents/phaser-2d/blob/main/src/scripts/scenes/mainScene.ts#L40-L42
The bug was the wrong bytecode was being used and after updating the bytecode the tests pass

:white_check_mark: Test: Add a test for a pure function

---

.github/workflows/prerelease.yml

:construction_worker: Chore: Remove unnecessary build step from prepublish

---

.changeset/warm-swans-explode.md
bundler/config/docs/modules/defaultConfig.md
bundler/config/docs/modules/defineConfig.md
bundler/config/docs/modules/types.md
bundler/config/src/config/validateUserConfig.js
bundler/config/src/config/withDefaults.js
bundler/config/src/config/withDefaults.spec.ts
bundler/config/src/defineConfig.spec.ts
bundler/config/src/loadConfig.spec.ts
bundler/config/src/types.ts
bundler/docs/modules/evmts_config.defaultConfig.md
bundler/docs/modules/evmts_config.defineConfig.md
bundler/docs/modules/evmts_config.types.md
bundler/ts-plugin/src/decorators/getScriptSnapshot.ts
bundler/ts-plugin/vitest.config.ts

Adds debug as an option to evmts/config

:sparkles: Feat(config): Add debug as a configuration option

---

.changeset/purple-drinks-beg.md

Bump versions because a bug with webpack plugin

:bookmark: Chore: bump alpha versions

---

.changeset/neat-impalas-dream.md
bundler/solc/package.json
pnpm-lock.yaml

Fix bug with @evmts/resolution being listed as a dev dep rather than runtime dep

:bug: Fix(solc): Fix bug with dev dep that should be regular dep

---

.changeset/lucky-dolphins-grin.md
bundler/base/package.json
bundler/bun/package.json
bundler/config/package.json
bundler/resolutions/package.json
bundler/runtime/package.json
bundler/solc/package.json
bundler/ts-plugin/package.json
bundler/unplugin/package.json
extensions/viem/package.json
packages/blockexplorer/package.json
packages/effect/package.json
packages/schemas/package.json
pnpm-lock.yaml

Effect fails when versions mismatch

:bug: Fix: Fix version mismatch issues with effect

---

.changeset/silver-queens-juggle.md
bundler/config/package.json
extensions/viem/package.json
packages/blockexplorer/package.json
packages/effect/package.json
packages/schemas/package.json
pnpm-lock.yaml

Version mismatch causing issues

:bookmark: Fix: Update effect schema

---

.changeset/plenty-numbers-hear.md

Add changeset for https://github.com/evmts/evmts-monorepo/pull/692

:bookmark: Chore: Add changeset for evmts/runtime fix

---

bundler/ts-plugin/package.json
bundler/ts-plugin/src/utils/solidityModuleResolver.spec.ts
bundler/ts-plugin/src/utils/solidityModuleResolver.ts
bundler/ts-plugin/vitest.config.ts
pnpm-lock.yaml

Fix bug with failing to resolve a node module import

:bug: Fix(ts-plugin): Fix node module resolution

---

.nxignore

Add nx ignore to remove lib from nx affected files

:construction_worker: Chore: Add .nxignore

---

nx.json

Improve caching of build:types and test:coverage

:zap: chore: Improve caching of nx.json

---

nx.json
vercel.json

Fix vercel build that has been broken for over a month

:bug: fix: Vercel deployment

---

.changeset/sweet-ladybugs-add.md
bundler/config/src/tsconfig/getEvmtsConfigFromTsConfig.js
bundler/config/src/tsconfig/getEvmtsConfigFromTsConfig.spec.ts
bundler/config/src/tsconfig/loadTsConfig.js
bundler/config/vitest.config.ts

Added ability to solve the most common case of using tsconfig paths

:sparkles: Feat(config): Add ability to resolve tsconfig paths

---

.changeset/shaggy-shoes-attend.md
bundler/config/src/loadConfig.spec.ts
bundler/config/src/tsconfig/getEvmtsConfigFromTsConfig.js
bundler/config/src/tsconfig/getEvmtsConfigFromTsConfig.spec.ts
bundler/config/src/tsconfig/loadTsConfig.js
bundler/config/vitest.config.ts
bundler/ts-plugin/src/decorators/resolveModuleNameLiterals.ts
bundler/ts-plugin/vitest.config.ts

Resolve remappings in tsconfig

:bug: Feat: use remappings in tsconfig

---

vm/docs/classes/EVMts.md
vm/docs/modules.md
vm/package.json
vm/src/evmts.ts
vm/src/stateManager/EthersStateManager.ts
vm/src/stateManager/ViemStateManager.ts
vm/tsup.config.ts

Issues with package including
- bad folder path (copy pasta)
- linking to wring esm/cjs modules in package.json
- not compiling cjs

:bug: Fix(vm): Fix issues with tsup and package.json

---

bundler/solc/src/index.js

Fix bug with not exporting a solc util

:bug: Fix(solc): Export new solc util

---

.changeset/empty-turkeys-impress.md
bundler/unplugin/src/evmtsUnplugin.js
bundler/unplugin/vitest.config.ts

:bug: Fix(unplugin): strangling console.log

---

lsp/lsp/bin/evmts-lsp.js
lsp/lsp/package.json
lsp/lsp/src/index.ts
lsp/lsp/src/language.ts
lsp/lsp/tsconfig.json
lsp/ts-plugin/package.json
lsp/vscode/.vscodeignore
lsp/vscode/package.json
lsp/vscode/scripts/build.js
lsp/vscode/src/extension.ts
lsp/vscode/tsconfig.json
pnpm-lock.yaml

Copy in starter projects for volar

:package: Chore: Add boilerplate for volar server and vscode extension

---

packages/schemas/docs/classes/common.InvalidBlockNumberError.md
packages/schemas/docs/classes/common.InvalidUrlError.md
packages/schemas/docs/classes/ethereum.InvalidAddressError.md
packages/schemas/docs/classes/ethereum.InvalidBytesError.md
packages/schemas/docs/classes/ethereum.InvalidBytesFixedError.md
packages/schemas/docs/classes/ethereum.InvalidINTError.md
packages/schemas/docs/classes/ethereum.InvalidUINTError.md
packages/schemas/docs/classes/evmts.InvalidAddressBookError.md

:memo: Chore: Update md files

---

.github/workflows/prerelease.yml
.github/workflows/release.yml
.github/workflows/snapshot.yml

Fix workflows that have wrong org after changing name`

:bug: Fix: Workflows

---

examples/vite/tevm.config.json
examples/vite/tsconfig.json

:recycle: Chore: Update example app to use config file

---

.changeset/soft-trains-unite.md
vm/vm/src/Tevm.ts
vm/vm/src/createTevm.js
vm/vm/src/jsonrpc/createHttpHandler.ts

Forward unknown json rpc methods to the underlying fork

:sparkles: Feat: Forward unknown json rpc requests to underlying fork

---

package.json

Add bun all:clean command that will build entire repo clean

:technologist: Feat: Add bun all:clean command for building clean

---

package.json

Remove nx cache on clean so it cleans fresh.

:construction_worker: Fix: Remove nx cache on clean

---

vm/procedures/src/handlers/contractHandler.spec.ts
vm/procedures/src/handlers/scriptHandler.js
vm/procedures/src/handlers/scriptHandler.spec.ts
vm/procedures/src/jsonrpc/callProcedure.js
vm/procedures/src/jsonrpc/scriptProcedure.js
vm/procedures/src/requestProcedure.spec.ts

:white_check_mark: Test: Add 100% test coverage to vm handlers

---

README.md

:fire: Feat: Remove the EVMts logo

---

README.md

:memo: Chore: Use tevm package instead of tevm/contracts for download numbers

---

vercel.json

:construction_worker: Chore: Point at new docs site

---

vm/api/src/TevmJsonRpcRequestHandler.ts

:bug: Fix(api): Docs fixes

---

.changeset/config.json
.changeset/rare-comics-clap.md

Changesets were broken from previous prs and missing changesets added to packages

:bug: Fix: changesets

---

.changeset/angry-foxes-report.md
.changeset/early-bugs-rush.md
.changeset/fifty-insects-rest.md
.changeset/friendly-mangos-beam.md
.changeset/great-grapes-lay.md
.changeset/metal-turkeys-call.md
.changeset/pre.json
.changeset/purple-donkeys-smile.md
.changeset/quiet-eagles-sniff.md
.changeset/rare-comics-clap.md
.changeset/red-timers-sip.md
.changeset/shy-clouds-teach.md
.changeset/spicy-paws-refuse.md

More broken changesets from name change

:bug: Fix: Update more broken changesets

---

.changeset/twelve-rockets-know.md
packages/memory-client/src/CreateEVMOptions.ts
packages/memory-client/src/createMemoryClient.js

:sparkles: Feat: Add more tevm memory options

---

docs/astro.config.mjs

:bug: Fix: edit link

---

docs/src/content/docs/index.mdx
package.json

:construction_worker: Chore: explicit publish command

---

.changeset/fast-socks-ring.md
bundler/package.json
docs/astro.config.mjs
pnpm-lock.yaml

:bug: Fix: Move deps to dependencies for @tevm/bundler package

---

packages/procedures-types/src/requests/EthJsonRpcRequest.ts

Fix a bug where the type of eth_* params were not serialized into hex

:bug: Fix(procedures-types): Fix eth param that should be serialized to json

---

.changeset/yellow-pugs-buy.md

:bug: Fix: Broken changeset

---

.changeset/yellow-pugs-buy.md
docs/src/content/docs/index.mdx
docs/src/content/docs/learn/reference/index.md

:memo: Add precompile package to docs reference page

---

vm/bunfig.toml
vm/plugins.ts

:fire: Fix: remove unused files

---

.changeset/early-tips-repeat.md

:arrow_up: Chore: Bump barrel package version

---

.changeset/config.json
.changeset/fast-ants-run.md

:bug: Fix: Link tevm to changeset linked packages

---

.changeset/silver-dodos-clean.md
bundler-packages/debuglogs.txt
docs/src/content/docs/learn/actions/index.md
docs/src/content/docs/learn/clients/index.md
docs/src/content/docs/reference/@tevm/client-types/type-aliases/TevmClient.md
docs/src/content/docs/reference/@tevm/procedures-types/API.md
docs/src/content/docs/reference/@tevm/procedures-types/type-aliases/TevmJsonRpcBulkRequestHandler.md
docs/src/content/docs/reference/@tevm/procedures/API.md
docs/src/content/docs/reference/@tevm/procedures/functions/requestBulkProcedure.md
examples/svelte-ethers/package.json
examples/svelte-ethers/vite.config.js
examples/vite/package.json
examples/vite/vite.config.ts
pnpm-lock.yaml

Add documentation for errors as values

:memo: Docs: Document actions returning errors as values

---

packages/state/README.md
packages/state/src/Cache.ts
packages/state/src/ForkStateManager.ts
packages/state/src/NormalStateManager.ts
packages/state/src/ParameterizedAccountStorage.ts
packages/state/src/ProxyStateManager.ts

Update files that are highly adapted from ethereumjs state manager

:page_facing_up: Fix: Update ethereumjs licensed files

---

packages/state/README.md
packages/state/src/Cache.ts
packages/state/src/ForkStateManager.ts
packages/state/src/NormalStateManager.ts
packages/state/src/ParameterizedAccountStorage.ts
packages/state/src/ProxyStateManager.ts

:recycle: Make proxy state manager more like the upstream version

---

docs/src/content/docs/getting-started/quick-start.md

Fixed bad link in docs from moved util

:memo: Fix: Docs bad link

---

docs/src/content/docs/learn/clients/index.md

Fixes https://github.com/evmts/tevm-monorepo/issues/968

:memo: Fix: Bad import in docs

---

README.md

:memo: Docs: Feature emojis like ponder README.md

---

.nxignore

:construction_worker: Fix: add generated docs to nx ignore

---

.changeset/three-drinks-run.md

:bookmark: Chore: missing changeset

---

packages/common/src/index.ts

:construction: Feat(common): Export ConsensusAlgorithm type

---

CONTRIBUTING.md

:memo: Chore: update contributing.md

---

bundler-packages/bun/package.json
bundler-packages/bundler-cache/package.json
bundler-packages/unplugin/package.json
extensions/ethers/package.json
extensions/viem/package.json
lsp/ts-plugin/package.json
packages/actions-types/package.json
packages/actions/package.json
packages/block/package.json
packages/blockchain/package.json
packages/client-types/package.json
packages/common/package.json
packages/contract/package.json
packages/decorators/package.json
packages/evm/package.json
packages/http-client/package.json
packages/memory-client/package.json
packages/precompiles/package.json
packages/procedures-types/package.json
packages/procedures/package.json
packages/server/package.json
packages/state/package.json
packages/sync-storage-persister/package.json
packages/txpool/package.json
packages/vm/package.json
pnpm-lock.yaml
test/bench/package.json

:package: Chore: Make the way we reference packages consistent

---

.changeset/config.json
test/mdt-repro/package.json

:construction_worker: Fix: Add mdt-repro to changeset ignore

---

docs/src/content/docs/getting-started/quick-start.md
package.json

:memo: Fix: Bad formatting quickstart

---

docs/src/content/docs/index.mdx

:memo: Fix: Add coming soon to broken stackblitz

---

docs/src/content/docs/getting-started/getting-started.md
docs/src/content/docs/learn/actions/index.md
docs/src/content/docs/learn/clients/index.md
docs/src/content/docs/reference/@tevm/ethers/classes/TevmProvider.md
docs/src/content/docs/reference/@tevm/memory-client/functions/createMemoryClient.md
docs/src/content/docs/reference/@tevm/memory-client/type-aliases/MemoryClient.md
docs/src/content/docs/reference/@tevm/server/functions/createHttpHandler.md
extensions/ethers/docs/classes/TevmProvider.md
extensions/ethers/src/TevmProvider.js
packages/memory-client/docs/functions/createMemoryClient.md
packages/memory-client/docs/type-aliases/MemoryClient.md
packages/memory-client/src/MemoryClient.ts
packages/memory-client/src/createMemoryClient.js
packages/server/docs/functions/createHttpHandler.md
packages/server/src/createHttpHandler.js
tevm/docs/index/type-aliases/MemoryClient.md

:memo: Feat: Update docs based on breaking changes

---

CONTRIBUTING.md

:busts_in_silhouette: Chore: Update CONTRIBUTING.md

---

packages/memory-client/src/test/viemPublicActions.spec.ts

:white_check_mark: Test: Uncomment flaky test

---

README.md

:memo: Docs: Update README.md

---

.changeset/large-waves-collect.md
docs/src/content/docs/learn/clients/index.md
docs/src/content/docs/reference/@tevm/actions/functions/callHandler.md
packages/actions/docs/functions/callHandler.md
packages/actions/src/tevm/callHandler.js
packages/base-client/src/createBaseClient.js
packages/base-client/src/createBaseClient.spec.ts
packages/memory-client/src/test/miningModes.spec.ts
packages/memory-client/src/test/requests.spec.ts

:sparkles: Feat: Add support for automining

---

.changeset/curly-mirrors-sing.md
lsp/ts-plugin/src/bin/tevm-gen.ts

:bug: Fix: shebang in cli script

---

README.md

📜 docs: Update README.md

---

.changeset/clever-wasps-fry.md
.changeset/silent-panthers-camp.md

:construction_worker: Fix: remove bad changeset

---

.changeset/ten-apricots-sell.md

:bookmark: Changeset

---

docs/astro.config.mjs
docs/src/content/docs/learn/actions/index.md
docs/src/content/docs/learn/contracts/index.md
docs/src/content/docs/learn/json-rpc/index.md

:memo: Docs: Update contract docs

---

.changeset/sour-peaches-sin.md
bundler-packages/runtime/src/generateTevmBodyDts.js

:bug: Fix: DTS bug

---

packages/common/package.json
pnpm-lock.yaml

:bug: Fix: Bad package.json common

---

examples/next/next.config.mjs

:wrench: Feat: Update next.config

---

.changeset/brown-foxes-doubt.md

:bug: Fix: remove major from a changeset

---

experimental/revm/package.json
experimental/schemas/package.json
experimental/solc/package.json
experimental/viem-effect/package.json

:bug: Fix: remove major from a changeset (#1256)

---

.changeset/thin-pens-nail.md
packages/procedures/src/anvil/anvilSetCoinbaseProcedure.js

:bug: Fix: anviLSetcoinbase bug

---

.changeset/sharp-clocks-deny.md
packages/actions/docs/functions/callHandler.md
packages/actions/docs/functions/forkAndCacheBlock.md
packages/actions/src/Call/__snapshots__/callHandler.spec.ts.snap
packages/actions/src/Call/__snapshots__/callHandlerOpts.spec.ts.snap
packages/actions/src/Call/__snapshots__/cloneVmWithBlock.spec.ts.snap
packages/actions/src/Call/__snapshots__/handleEvmError.spec.ts.snap
packages/actions/src/Call/__snapshots__/validateCallParams.spec.ts.snap
packages/actions/src/Call/callHandler.js
packages/actions/src/Call/callHandlerOpts.js
packages/actions/src/Call/callHandlerOpts.spec.ts
packages/actions/src/Call/cloneVmWithBlock.js
packages/actions/src/Call/cloneVmWithBlock.spec.ts
packages/actions/src/Call/handleEvmError.spec.ts
packages/actions/src/Call/handlePendingTransactionWarning.spec.ts
packages/actions/src/Call/handlePendingTransactionsWarning.js
packages/actions/src/Call/handleTransactionCreation.js
packages/actions/src/Call/validateCallParams.js
packages/actions/src/Call/validateCallParams.spec.ts
packages/actions/src/GetAccount/getAccountHandler.spec.ts
packages/actions/src/SetAccount/validateSetAccountParams.js
packages/actions/src/internal/forkAndCacheBlock.js
packages/actions/src/internal/forkAndCacheBlock.spec.ts

:recycle: Test: 100% test coverage for tevmCall

---

nx.json

:wrench: Chore: Remove deprecated prop from nx.json

---

.changeset/bright-seahorses-care.md
.changeset/clean-mirrors-jog.md
.changeset/rare-numbers-grin.md
packages/actions/docs/functions/callHandler.md
packages/actions/docs/functions/callHandlerOpts.md
packages/actions/docs/functions/validateContractParams.md
packages/actions/docs/type-aliases/ContractParams.md
packages/actions/docs/type-aliases/ValidateContractParamsError.md
packages/actions/src/Call/__snapshots__/callHandler.spec.ts.snap
packages/actions/src/Call/__snapshots__/handleTransactionCreation.spec.ts.snap
packages/actions/src/Call/callHandler.js
packages/actions/src/Call/callHandler.spec.ts
packages/actions/src/Call/callHandlerOpts.js
packages/actions/src/Call/handleTransactionCreation.js
packages/actions/src/Call/handleTransactionCreation.spec.ts
packages/actions/src/Contract/ContractHandlerType.spec.ts
packages/actions/src/Contract/ContractParams.ts
packages/actions/src/Contract/__snapshots__/contractHandler.spec.ts.snap
packages/actions/src/Contract/__snapshots__/createScript.spec.ts.snap
packages/actions/src/Contract/__snapshots__/validateContractParams.spec.ts.snap
packages/actions/src/Contract/contractHandler.spec.ts
packages/actions/src/Contract/createScript.js
packages/actions/src/Contract/createScript.spec.ts
packages/actions/src/Contract/validateContractParams.js
packages/actions/src/Contract/validateContractParams.spec.ts
packages/actions/src/Script/ScriptHandlerType.spec.ts
tevm/docs/index/type-aliases/ContractParams.md

:white_check_mark: Test: Add more test coverage to tevm/actions

---

.changeset/happy-mails-provide.md
.changeset/sharp-suits-happen.md
packages/actions/src/Call/__snapshots__/callHandler.spec.ts.snap
packages/actions/src/Call/callHandler.js
packages/actions/src/Call/callHandler.spec.ts
packages/actions/src/DumpState/dumpStateHandler.js
packages/actions/src/GetAccount/getAccountHandler.js
packages/actions/src/Mine/mineHandler.js
packages/actions/src/eth/ethGetLogsHandler.js
packages/actions/src/eth/getBalanceHandler.js
packages/actions/src/eth/getCodeHandler.js
packages/actions/src/eth/getStorageAtHandler.js
packages/actions/src/internal/getPendingClient.js
packages/actions/src/internal/getPendingClient.spec.ts
packages/blockchain/src/utils/__snapshots__/getBlockFromRpc.spec.ts.snap
packages/blockchain/src/utils/warnOnce.js

:white_check_mark: Feat: Pending client test coverage

---

extensions/viem/README.md
lsp/lsp/README.md
lsp/vscode/README.md

:memo: Docs: update some readmes

---

.changeset/brave-goats-ring.md
bundler-packages/config/docs/loadConfig/classes/LoadConfigError.md
bundler-packages/config/docs/loadConfig/functions/loadConfig.md
bundler-packages/config/docs/loadConfig/type-aliases/LoadConfigErrorType.md
bundler-packages/config/scripts/runFixture.ts
bundler-packages/config/src/fixtures/withRemappingsTxt/remappings.txt
bundler-packages/config/src/fixtures/withRemappingsTxt/tsconfig.json
bundler-packages/config/src/json/loadRemappingstxt.js
bundler-packages/config/src/loadConfig.js
bundler-packages/config/src/loadConfig.spec.ts

:sparkles: Feat: Support remappings.txt

---

.changeset/stale-cameras-drum.md

:bookmark: Fix: missing changeset

---

bundler-packages/tevm-run/package.json
pnpm-lock.yaml

:bug: Fix: bad package.json

---

.changeset/pre.json
pnpm-lock.yaml
tevm/bin/tevm.cjs
tevm/bin/tevm.js
tevm/package.json

:sparkles: Feat: Add temporary cli that matches correct shape

---

.changeset/light-cars-tease.md
tevm/package.json

:bug: Fix: Bad version

---

package.json
pnpm-lock.yaml

:arrow_down: Fix: downgrade changesets

---

package.json
packages/procedures/.gitignore
packages/procedures/CHANGELOG.md
packages/procedures/LICENSE
packages/procedures/README.md
packages/procedures/biome.json
packages/procedures/package.json
packages/procedures/src/index.ts
packages/procedures/tsconfig.json
packages/procedures/tsup.config.ts
packages/procedures/typedoc.json
packages/procedures/vitest.config.ts
pnpm-lock.yaml

:clown_face: Chore: HAck release into working

---

.changeset/smart-mice-dream.md
packages/actions/src/Call/callHandler.js
packages/actions/src/Call/callHandlerOpts.js
packages/actions/src/Call/callHandlerOpts.spec.ts
packages/actions/src/Call/callProcedure.spec.ts
packages/actions/src/Call/handleStateOverrides.js
packages/blockchain/src/utils/CUSTOM_Tx_TYPES.js
packages/blockchain/src/utils/getBlockFromRpc.js

:bug: Fix: add rest of arb tx types

---

bundler-packages/base-bundler/src/getContractPath.js

:zap: Fix: Remove bun warning from base-bundler

---

.changeset/new-books-accept.md
pnpm-lock.yaml

:bug: Changeset

---

docs/node/.gitignore
docs/node/docs/dist/llms-full.txt
docs/node/docs/dist/llms.txt
docs/node/docs/pages/api/json-rpc.mdx
docs/node/docs/pages/api/memory-client.mdx
docs/node/docs/pages/api/methods.mdx
docs/node/docs/pages/api/tevm-call.mdx
docs/node/docs/pages/core/create-tevm-node.mdx
docs/node/docs/pages/core/forking.mdx
docs/node/docs/pages/core/managing-state.mdx
docs/node/docs/pages/getting-started.mdx
docs/node/package.json
package.json
pnpm-lock.yaml

:truck: Chore: Split up docs into multiple docs sites

---

docs/node/docs/pages/getting-started.mdx

fix: Getting started common

---

.changeset/config.json

:wrench: Fix: broken changeset config

---

README.md

docs: New readme logo

---

README.md

:memo: Docs: better README.md

---

.gitmodules

:package: Chore: Add helios

---

docs/node/docs/pages/api/evm-events.mdx
docs/node/docs/pages/api/json-rpc.mdx
docs/node/docs/pages/api/tevm-call.mdx
docs/node/docs/pages/examples/viem.mdx
docs/node/docs/pages/getting-started/overview.mdx

docs: update docs to not use custom

---

.changeset/shiny-poets-cross.md
cli/package.json
cli/src/utils/server.ts

fix: cli ts build

---

docs/node/package.json
docs/node/pages/examples/ethers.mdx
pnpm-lock.yaml

Revert "fix: Broken docs (#1602)"

---

tevm/package.json

fix: clean script

---

flake.nix

chore: Add zig to nix

---

packages/txpool/src/TxPool.spec.ts
src/Evm/Frame_test.zig
src/Evm/evm.zig
src/Types/U256.spec.ts
src/Types/U256.ts
src/Types/common-int.ts
src/root.zig

feat: Add more units to U256

---

packages/txpool/src/TxPool.spec.ts
src/Evm/Frame_test.zig
src/Evm/evm.zig
src/Interpreter/interpreter.zig
src/Types/U256.spec.ts
src/Types/U256.ts
src/Types/common-int.ts
src/root.zig

fix: linter

---

src/Server/Server.ts
src/Server/main.zig
src/Server/middleware/Logger.zig
src/Server/server.zig

Refactored the server code to improve performance and readability. Key changes include:
- Added placeholder in Server.ts for future migration from packages/server
- Simplified the Logger middleware by using defer for timing measurements
- Removed unnecessary comments throughout the codebase
- Made JsonRpcRequest struct public for better accessibility
- Streamlined server initialization and request handling
The existing server test has been maintained and continues to validate that the server correctly handles JSON-RPC requests. The test creates a server on a test port, sends a request, and verifies the response contains the expected data.

chore: Server refactor

---

src/Interpreter/Memory.zig
src/Interpreter/Stack.zig

Implemented a complete Memory model for the Ethereum Virtual Machine (EVM). This replaces the placeholder implementation with a fully functional memory system that:
- Provides byte-addressable memory that grows as needed
- Implements core memory operations: set, set32, resize, getCopy, getPtr, copy
- Tracks memory size and gas costs
- Handles memory regions safely, including overlapping regions during copy operations
Added comprehensive test suite covering:
- Basic memory operations (resize, set, getCopy, getPtr)
- 32-byte value setting with proper big-endian representation
- Memory copying with both overlapping and non-overlapping regions
- Edge cases including empty memory, multiple resizes, and setting data at various offsets

feat: Implement Memory

---

src/Interpreter/JumpTable.zig
src/Interpreter/Memory.zig
src/Interpreter/Stack.zig

Added a new `JumpTable.zig` module to the Interpreter directory that implements the EVM opcode jump table functionality. This module defines the core structures and functions needed for opcode execution:
- `Operation` struct to represent EVM opcodes with execution functions, gas costs, and stack requirements
- `JumpTable` struct to manage the 256 possible opcodes
- Gas calculation constants and helper functions for stack validation
- Implementation of the Frontier instruction set
- Basic execution functions for operations like STOP
The implementation includes comprehensive test cases that verify:
- Basic JumpTable operations and initialization
- Proper handling of undefined opcodes
- Stack calculation helper functions
- Gas constant definitions
- JumpTable validation logic
Your …

feat: JumpTable

---

src/Interpreter/Contract_mock.zig
src/Interpreter/Contract_test.zig
src/Interpreter/InterpreterState.zig
src/Interpreter/JumpTable.zig
src/Interpreter/Memory.zig
src/Interpreter/Stack.zig
src/Interpreter/bitvec.zig
src/Interpreter/interpreter.zig
src/Interpreter/opcodes.zig

Enhanced the Contract module with comprehensive functionality for Ethereum contract execution. Added support for JUMPDEST analysis, gas management, and proper contract lifecycle handling. The implementation includes:
- Complete Contract struct with fields for address, code, gas tracking, and execution context
- JUMPDEST validation using efficient bitvector-based code analysis
- Gas management with useGas/refundGas methods
- Support for contract creation with parent context sharing
- Proper handling of opcodes and program counter management
Added comprehensive test suite in Contract_test.zig covering:
- Contract initialization and code setting
- Opcode retrieval and boundary checking
- Gas management functionality
- JUMPDEST validation for various scenarios
- Parent-child contract …

feat: Interpreter WIPing

---

build.zig

Added the `zabi` dependency to the project, which is a Zig library for working with ABI encoding/decoding. The dependency is imported into both the executable and library modules.
The changes have been verified to compile successfully with the new dependency.

feat: Add human readable abi support with zabi

---

package.json

Removed the unused `app` dependency from `package.json`.
Verified that the application builds and runs correctly without the removed dependency.

fix: app dep

---

CLAUDE.md
src/evm/CLAUDE.md
src/evm/frame.zig
src/evm/jump_table.zig
src/evm/stack.zig
src/evm/vm.zig
test/evm/stack_test.zig

Added `@branchHint` annotations to optimize performance in critical EVM execution paths. These hints help the compiler generate more efficient code by indicating which branches are more likely to be taken during execution.
Also cleaned up the Stack implementation by:
1. Removing redundant camelCase method aliases from the main implementation
2. Moving all camelCase aliases to a dedicated compatibility section at the end of the file
3. Adding branch hints to frequently used methods
Updated tests to use snake_case method names where appropriate.
All existing tests continue to pass with the updated method names. The changes are performance-oriented and don't affect functionality.

⚡ perf: Add @branchHint optimizations to EVM execution paths

---

TEVM_vs_EVMONE_COMPARISON.md
src/evm/README.md
src/evm/prompts/implement-cicd-wasm-size-check.md
src/evm/prompts/implement-gas-refunds-sstore.md
src/evm/prompts/implement-identity-precompile.md
src/evm/prompts/implement-ripemd160-precompile.md
src/evm/prompts/implement-selfdestruct-opcode.md
src/evm/prompts/implement-sha256-precompile.md
src/evm/prompts/implement-state-vtable-interface.md

- Create new prompts
- Add missing features

📝 planning: Document missing features

---

debug_call_test.zig
src/evm/execution/system.zig
test/evm/opcodes/control_system_comprehensive_test.zig
test/evm/opcodes/create_call_comprehensive_test.zig
test/evm/opcodes/system_test.zig
test_journal_simple.zig

Added snapshot and revert helper functions for opcode-level state management in the EVM execution system. These functions provide a clean API for creating, committing, and reverting state snapshots during opcode execution.
Added two test files:
- `debug_call_test.zig` to document expected EVM behavior for calls to EOAs
- `test_journal_simple.zig` with tests for basic journal functionality including balance, storage, and multiple state changes
Updated comments in existing tests to clarify that regular contract calls are not yet fully implemented in the VM.
Added comprehensive tests for the journal functionality, covering:
- Basic snapshot and revert operations
- Storage state changes
- Multiple state changes across different accounts
- Proper reversion of all state changes
Updated existing …

✨ feat: Implement journaling and state reverting

---

src/evm/evm.zig
src/evm/execution/execution_error.zig
src/evm/state/database_factory.zig
src/evm/state/database_interface.zig
src/evm/state/memory_database.zig
src/evm/state/state.zig
src/evm/state/storage_key.zig
src/evm/vm.zig
test/evm/opcodes/test_helpers.zig
test/evm/state/database_interface_test.zig
test/evm/static_call_protection_test.zig
test/evm/vm_opcode_test.zig
test_database_simple.zig

Implemented a pluggable database interface for EVM state management, allowing different storage backends to be swapped without changing core EVM logic. This includes:
- A vtable-based `DatabaseInterface` for runtime polymorphism
- A fast in-memory `MemoryDatabase` implementation
- A factory pattern for creating different database implementations
- Error handling for database operations
- Support for snapshots and batch operations
- Updated EVM state to use the database interface instead of direct storage
- Added comprehensive test suite for database interface compliance
- Tested memory database implementation with various edge cases
- Verified snapshot and batch operation functionality
- Updated existing VM tests to use the new database interface
- Added simple standalone test for …

✨ feat: Implement database interface

---

packages/actions/src/debug/debugTraceTransactionProcedure.spec.ts

Improved test structure for debug transaction tracing by reformatting contract deployment calls for better readability and replacing a skipped test with a todo placeholder.
- Maintained all existing test functionality while improving code formatting
- Removed unused imports (`EIP1193RequestFn` and `requestEip1193`)
- Converted a skipped test case (`it.skip`) to a todo placeholder (`it.todo`) for future implementation

fix: broken build
